### ISSUE TITLE
About Environment For xgraph/PGExplainer

### ISSUE THREAD

**Issue by neolifer** [divelab/DIG#10]
How do i get the required packages for xgraph/PGExplainer? The install.sh does not work for me.

**Comment by Oceanusity** [comment]
Hi, thanks for your issue. I have updated the install.sh file and add the required environments in the file.

**Comment by Gori-LV** [comment]
Just a very quick question, I see most the xgraph papers already have their own implementation, have you compare your experimental result with theirs? regarding both GNN performance/behavior and explanation result, do they align with each other? thanks!

**Comment by Oceanusity** [comment]
Thank you for your questions.
First, some methods such as GNN_LRP haven't released an official implementation yet, and the experiment settings are not clear. Thus, we follow the algorithms in their papers and get reasonable results.
Second, for some methods, we follow the official implementation in the packages or repositories and fit them into our framework. It's important that the explanation results are highly related to the parameters of GNN models, and some optimization-based methods may have different results with different initialization such as GNNExplainer. Therefore, we build the same GNN structures and transfer the provided model parameters to test some methods such as PGExplainer. 
In a word, we can guarantee the correctness of algorithm implementations but can't promise the results are exactly the same.

**Comment by Gori-LV** [comment]
I see, thanks a lot for prompt answering, this is a great project, thanks for sharing!
