### ISSUE TITLE
Explanation for the Trained Models

### ISSUE THREAD

**Issue by mahimanzum** [divelab/DIG#105]
Hi,
Thank you for sharing this very useful package. Are there any available explanations on how the models used for the Expandability (x-graphs) portion are trained? I mean the output shape or objective. I am trying to check If I can use all the explainable models on a single dataset like Tox-21. Please let me know if there are any available resources. Thanks.

**Comment by CM-BF** [comment]
Thank you for your issue.
I'm not sure I've fully understood your question. We train our models with a general PyG pipeline and Adam optimizer. About the output shape, you can check it here: [https://github.com/divelab/DIG/blob/dig/examples/xgraph/deeplift.ipynb](https://github.com/divelab/DIG/blob/dig/examples/xgraph/deeplift.ipynb).

**Comment by mahimanzum** [comment]
Hello, Sorry for not being specific. For example, I am trying to use pgExplainer in Tox21 dataset on the trained model. I am getting this error : "TypeError: cannot assign 'torch.FloatTensor' as parameter '__edge_mask__' (torch.nn.Parameter or None expected)" for pgexplainer.py:446 . Here is the code to reproduce the error.

`from dig.xgraph.method import PGExplainer
pg_explainer = PGExplainer(model, in_channels=600, device=device, explain_graph=True)

def index_to_mask(index, size):
    mask = torch.zeros(size, dtype=torch.bool, device=index.device)
    mask[index] = 1
    return mask

def split_dataset(dataset):
    indices = []
    num_classes = 2
    train_percent = 0.7
    for i in range(num_classes):
        index = (dataset.data.y == i).nonzero().view(-1)
        index = index[torch.randperm(index.size(0))]
        indices.append(index)

    train_index = torch.cat([i[:int(len(i) * train_percent)] for i in indices], dim=0)
    
    rest_index = torch.cat([i[int(len(i) * train_percent):] for i in indices], dim=0)
    rest_index = rest_index[torch.randperm(rest_index.size(0))]

    #print(train_index.size())
    dataset.data.train_mask = index_to_mask(train_index, size=dataset.data.num_nodes)
    dataset.data.val_mask = index_to_mask(rest_index[:len(rest_index) // 2], size=dataset.data.num_nodes)
    dataset.data.test_mask = index_to_mask(rest_index[len(rest_index) // 2:], size=dataset.data.num_nodes)
    print(dataset.data)
    dataset.data, dataset.slices = dataset.collate([dataset.data])

    return dataset


'''
splitted_dataset = split_dataset(dataset)
dataloader = DataLoader(splitted_dataset['test'], batch_size=1, shuffle=False)
'''
dataset = MoleculeDataset('datasets', 'Tox21')

#print(dataset)
dataset.data.x = dataset.data.x.to(torch.float32)
dataset.data.y = dataset.data.y[:, 2] # the target 2 task.

# dataset.data.y = dataset.data.y[:, 2]
dim_node = dataset.num_node_features
dim_edge = dataset.num_edge_features
# num_targets = dataset.num_classes
#num_targets = dataset.num_classes
num_classes = 2

splitted_dataset = split_dataset(dataset)

#print(splitted_dataset[0])

splitted_dataset.data.mask = splitted_dataset.data.test_mask
splitted_dataset.slices['mask'] = splitted_dataset.slices['train_mask']
dataloader = DataLoader(splitted_dataset, batch_size=1, shuffle=False)

pg_explainer.train_explanation_network(dataset)
torch.save(explainer.state_dict(), 'tmp.pt')
state_dict = torch.load('tmp.pt')
explainer.load_state_dict(state_dict)`

**Comment by Oceanusity** [comment]
Hello, there are example codes with PGExplainer and SubgraphX. Please refer to [PGExplainer](https://github.com/divelab/DIG/blob/dig-stable/examples/xgraph/pgexplainer.ipynb) and [SubgraphX](https://github.com/divelab/DIG/blob/dig-stable/examples/xgraph/subgraphx.ipynb). Also, you can find reference code in the [benchmark](https://github.com/divelab/DIG/tree/dig-stable/benchmarks/xgraph) directory providing examples of training models and explaining the model with multiple explainability methods.

**Comment by CM-BF** [comment]
I'll close this issue if no more discussion.
