### ISSUE TITLE
A question about DeepLift

### ISSUE THREAD

**Issue by for-just-we** [divelab/DIG#106]
Does the implemented DeepLift provide edge-level explanation result for each edge? I wonder whether DeepLift could be reimplemented in a node-level version, that calculation a score for each node.

**Comment by for-just-we** [comment]
Another question, could xxgraph support dgl, the PyG version I use only support homogeneous graph,  dgl seems to support 
Heterogeneous graph.

**Comment by CM-BF** [comment]
Thank you for your questions.

The vanilla implementation of DeepLIFT is at the node level. And the node score is mapped to edge scores naively. If you want to use node scores, I suggest you install our repo locally by `pip install -e .` and modified the output. Happy hacking.

The answer to the second question is yes. We are going to release a new version DIG that will support the latest PyG version. However, we don't have a plan to support dgl, currently.

**Comment by for-just-we** [comment]
> Thank you for your questions.
> 
> The vanilla implementation of DeepLIFT is at the node level. And the node score is mapped to edge scores naively. If you want to use node scores, I suggest you install our repo locally by `pip install -e .` and modified the output. Happy hacking.
> 
> The answer to the second question is yes. We are going to release a new version DIG that will support the latest PyG version. However, we don't have a plan to support dgl, currently.

Thank you, I have one more question. could xxgraph support heterogeneous graph?
