### ISSUE TITLE
GNNExplainer: optimization on the whole graph

### ISSUE THREAD

**Issue by alirezadizaji** [divelab/DIG#110]
Hi
as I understood, the only option for node-based explanation is to choose a subgraph with the same k-hop with the original model. is it possible to choose the k-hop of GNNExplainer arbitrarily? I believe the `subset` generated by the `subgraph` method could help this matter.

**Comment by Oceanusity** [comment]
Hello,  since the node information aggregates from its k-hop neighbors for a k-layer GNN, it's defaulted to explain the importance of its k-hop neighbors.

**Comment by Oceanusity** [comment]
Such k-hop neighbors all contribute to the final prediction of this node. Therefore, the explainability method such as GNNExplainer should consider them all in the algorithm.
