### ISSUE TITLE
Error in running DimeNetPP

### ISSUE THREAD

**Issue by LanceKnight** [divelab/DIG#115]
Hello, I've write a simple script to test DimeNetPP. However I got an error like this: 
![image](https://user-images.githubusercontent.com/5760199/178847555-38d11aa2-e3ee-4817-9683-01e76e5604ec.png)

```
from torch_geometric.datasets import QM9
from torch_geometric.loader import DataLoader
import torch
from torch_geometric.nn.acts import swish
from dig.threedgraph.method import DimeNetPP
from dig.threedgraph.evaluation import ThreeDEvaluator


dataset = QM9(root='/tmp/')

split_idx = {'train':list(range(1,1000)), 'valid':list(range(1000,1200)), 'test':list(range(2000,2200))}
train_dataset, valid_dataset, test_dataset = dataset[split_idx['train']], dataset[split_idx['valid']], dataset[split_idx['test']]


model = DimeNetPP(energy_and_force=False, cutoff=5.0, num_layers=4, 
				  hidden_channels=128, out_channels=1, int_emb_size=64, 
				  basis_emb_size=8, out_emb_channels=256, num_spherical=7, 
				  num_radial=6, envelope_exponent=5, num_before_skip=1, 
				  num_after_skip=2, num_output_layers=3, act=swish, 
				  output_init='GlorotOrthogonal')

loss_func = torch.nn.L1Loss()
evaluation = ThreeDEvaluator()

device= 'cuda:0'
loader = DataLoader(dataset)
print(f'size of loader:{len(loader)}')
for i, data_batch in enumerate(loader):
	model.to(device)
	data_batch.to(device)
	pred = model(data_batch)
	if i%500 ==0:
		print(data_batch.x.device)
		print(pred.shape)
```

I used QM9 from pyg on deliberately because my real data input is not .csv and does not have attributes such as 'z'. So I would like to see if this model works for a simpler data input.

Also, the pyg-nightly has updated 

`act` to `from torch_geometric.nn.resolver import activation_resolver`

**Comment by limei0307** [comment]
Hi @LanceKnight, 

This issue is due to the version of pytorch. Please see #77 for detail. I have updated the code [here](https://github.com/divelab/DIG/commit/861028f521051ba9ed4cba5a46d2c0953d544353). Please help to check. 

Thanks,
Limei

**Comment by LanceKnight** [comment]
Hi, @limei0307 , Thanks for the answer. But how do I update this code from the git? I used pip to upgrade to the latest codes, but the latest codes do not have this update. Do I need to manually change the library codes?

**Comment by limei0307** [comment]
Hi @LanceKnight, you can try to [install from source](https://github.com/divelab/DIG#install-from-source) with
`
git clone https://github.com/divelab/DIG.git
cd DIG
pip install .
`
, or just update code manually. Thanks.

**Comment by LanceKnight** [comment]
I see. Thanks!
