### ISSUE TITLE
KeyError: 'conv1.lin.weight'

### ISSUE THREAD

**Issue by MishanyaGeniyInformatiki** [divelab/DIG#121]
Hi there!
I use DIG. I'm trying to run a code from the 'Tutorial for GNN Explainability'.
```python
import torch
import os.path as osp
from dig.xgraph.dataset import SynGraphDataset
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
dataset = SynGraphDataset('./datasets', 'BA_shapes')
dataset.data.x = dataset.data.x.to(torch.float32)
dataset.data.x = dataset.data.x[:, :1]
dim_node = dataset.num_node_features
dim_edge = dataset.num_edge_features
num_classes = dataset.num_classes
```
```python
def check_checkpoints(root='./'):
    if osp.exists(osp.join(root, 'checkpoints')):
        return
    url = ('https://github.com/divelab/DIG_storage/raw/main/xgraph/checkpoints.zip')
    path = download_url(url, root)
    extract_zip(path, root)
    os.unlink(path)

from dig.xgraph.models import GCN_2l
model = GCN_2l(model_level='node', dim_node=dim_node, dim_hidden=300, num_classes=num_classes)
model.to(device)
check_checkpoints()
ckpt_path = osp.join('checkpoints', 'ba_shapes', 'GCN_2l', '0', 'GCN_2l_best.ckpt')
model.load_state_dict(torch.load(ckpt_path)['state_dict'])
```
Versions of installed packages:
python 3.10.4
pwtorch 1.12.0
torch-geometric 2.0.4
dive-into-graphs 0.1.2

But I get an error:
![Снимок экрана от 2022-07-19 01-17-42_cut-photo ru](https://user-images.githubusercontent.com/76114881/179630369-b7a7f986-63c2-4437-ac86-438b398c7e46.png)
What can it mean? The model does not find the necessary weights in GCN_2l_best.ckpt?

**Comment by CM-BF** [comment]
Thank you for reminding me. The Tutorial example is a little out of time. We will fix it soon. Please refer to the PyG2.0 version: https://github.com/divelab/DIG/blob/dig-stable/examples/xgraph/gnnexplainer.ipynb

**Comment by CM-BF** [comment]
Since there is no more discussions, I will close this issue.
