### ISSUE TITLE
SchNet: How to get graph embedding instead of prediction

### ISSUE THREAD

**Issue by LanceKnight** [divelab/DIG#122]
Hello, it seems the output of SchNet is of dimension 1, which is the prediction dimension. Is it possible to change to output the graph embedding instead of the predicton? This way it's more flexible for the users to put whatever downstream classifier after the embedding and have a control of how many prediction dimension there can be (multi-task potentially)

**Comment by limei0307** [comment]
Hi @LanceKnight, 

Thanks for your suggestion. We exactly followed the SchNet paper and fixed the output dimension as 1. I updated our code [here](https://github.com/divelab/DIG/commit/652651ab229a89239334a364c674b3ee1ea901eb) so that users can define the output dimension. 

Thanks,
Limei

**Comment by LanceKnight** [comment]
Thank you! @limei0307
