### ISSUE TITLE
BA-2Motif dataset

### ISSUE THREAD

**Issue by alirezadizaji** [divelab/DIG#127]
Hi,
Thanks for sharing datasets, I have a question about BA-2Motif dataset. I printed dataset and it shows this `Data(edge_index=[2, 50960], x=[25000, 10], y=[1000])` and as `y` shows it has 1000 samples but why the first dimension of `edge_index` and `x` is not 1000 too? 
also is there any pretrained graph/node level GCN model on this dataset?

**Comment by Oceanusity** [comment]
hello, in ba-2motif.dataset, it has 1000 graphs with 25 nodes. That's to say, it has 25000 different nodes in this dataset.

**Comment by alirezadizaji** [comment]
I see thanks, but what about my 2nd question?

**Comment by Oceanusity** [comment]
Yes, we have pre-trained models on this dataset. Please refer to the codes in the benchmark.
https://github.com/divelab/DIG/tree/dig-stable/benchmarks/xgraph

**Comment by Oceanusity** [comment]
BA-2Motif is a graph classification dataset. Therefore, we compare different explainability methods with graph-level classification GCN in this benchmark.
