### ISSUE TITLE
Global features in graph generation

### ISSUE THREAD

**Issue by gooaah** [divelab/DIG#128]
Dear developers,

I am trying to produce crystal structures by graph generative models (like GraphDF) provided in DIG. Can these models generate global features of graph (e.g.  the cell of crystal)? If so, how can I construct a new dataset of crystals to train generative models?

Thanks!

**Comment by lyzustc** [comment]
Hi gooaah,

Thank you for your interest in DIG! The graph generative models in DIG can only generate molecular graph structures, including atom types (e.g., carbon, oxygen) and chemical bond types. The global features like crystal cell cannot be generated in our methods.

Best regards,
Youzhi Luo

**Comment by gooaah** [comment]
Thanks!
