### ISSUE TITLE
No module named 'vocab'

### ISSUE THREAD

**Issue by yyou1996** [divelab/DIG#13]
Hello DIG team,

In JT-VAE sub-repo (https://github.com/divelab/DIG/tree/main/dig/ggraph/JT-VAE#i-building-the-vocabulary), when I run `python mol_tree.py --data_file "moses.csv"`, it outcomes:
```
File "mol_tree.py", line 4, in <module>
from chemutils import get_clique_mol, tree_decomp, get_mol, get_smiles, set_atommap, enum_assemble, decode_stereo
File "/ssd2/yuning/graphcl/pregnn/chem/dataset/jt_vae/JT-VAE/chemutils.py", line 7, in <module>
from vocab import Vocab
ModuleNotFoundError: No module named 'vocab'
```

**Comment by yyou1996** [comment]
I copy the `vocab.py` from https://github.com/wengong-jin/icml18-jtnn/tree/master/fast_jtnn and it runs. Not sure whether it is the right way to fix it.

**Comment by borao** [comment]
Hello @yyou1996,

Thank you for raising this issue. The `vocab.py` is necessary to build the vocabulary after performing the tree decomposition. I have added it to the DIG JT-VAE source.
