### ISSUE TITLE
Using gnn explainer with mask_feature option

### ISSUE THREAD

**Issue by alirezadizaji** [divelab/DIG#134]
Hi,
I was trying to use `mask_feature` option in gnn explainer, but I got an error telling me `self.coeffs` is not defined. I also tried to find its defintion within the class and its parent but didn't find anything.
https://github.com/divelab/DIG/blob/d43d5845d047ed106b0cc396f7488d9ccbe4bb37/dig/xgraph/method/gnnexplainer.py#L57

**Comment by CM-BF** [comment]
Sorry about the inconvenience. Somebody changed the code without careful check. I'll fix it as soon as possible.
