### ISSUE TITLE
how to run set sparsity for subgraphx

### ISSUE THREAD

**Issue by Usama113** [divelab/DIG#137]
Hi,
    I am running experiments on dig-stable branch trying to reproduce the results in figure 6 and figure 7. I am running subgraphx.py code in benchmark/xgraph . I see in the config file, for subgraphx, there is no sparsity parameter like other exlpainers have. How can I control the sparsity for subgraphx. Thanks in advance.

**Comment by Oceanusity** [comment]
Hello, the sparsity is controlled by the parameter `max_nodes`. which is called `config.explainers.max_ex_size` in the configuration files.
