### ISSUE TITLE
GNNExplainer `mask_features` option

### ISSUE THREAD

**Issue by alirezadizaji** [divelab/DIG#139]
`mask_features` option is an argument of `forward` for GNNExplainer but it is not passed to `gnn_explainer_alg`. I actually have fixed and merged it to dig branch but not to dig-stable.
https://github.com/divelab/DIG/blob/d2d648f7c5ab915ad64eff1c22660a84bba6d755/dig/xgraph/method/gnnexplainer.py#L160

**Comment by Oceanusity** [comment]
Thank you for pointing it out. I have added the parameter `mask_features` to this function.
