### ISSUE TITLE
Where is 'vae_train.py' file?

### ISSUE THREAD

**Issue by yyou1996** [divelab/DIG#14]
Hello DIG team,

In https://github.com/divelab/DIG/tree/main/dig/ggraph/JT-VAE#3-training-1, the training script is
```
$ mkdir vae_model
$ python vae_train.py --train moses-processed --vocab vocab.txt --save_dir vae_model/
```
But seems that `vae_train.py` is missing.

Also `sample.py` in https://github.com/divelab/DIG/tree/main/dig/ggraph/JT-VAE#4-evaluation-1 is missing.

**Comment by borao** [comment]
Hello @yyou1996, these files have been added to the JT-VAE implementation, [here (vae_train)](https://github.com/divelab/DIG/blob/main/dig/ggraph/JT-VAE/vae_train.py) and [here (sample)](https://github.com/divelab/DIG/blob/main/dig/ggraph/JT-VAE/sample.py), respectively.

**Comment by yyou1996** [comment]
Thank you for fixing it.
