### ISSUE TITLE
PGExplainer - Visualization for Graphs Explanations 

### ISSUE THREAD

**Issue by matekenya** [divelab/DIG#140]
I'd like to create visualisations for the explanations of graph predictions. I have followed along with the documentation and I am currently meeting the following problem.

```
from dig.xgraph.method.pgexplainer import PlotUtils
plotutils = PlotUtils(dataset_name='bbbp', is_show=True)
data = get_datasets()['bbbp_dataset'][0]
x_collector = XCollector()
model = get_models(dim_classes, dim_node)['GIN_2L']
explainer = PGExplainer(model, in_channels=256, device=device, explain_graph=True)
with torch.no_grad():
    _, masks, related_preds = explainer(data.x, data.edge_index)
    x_collector.collect_data(masks, related_preds)

print('Data: ', data)
print('Plotutils: ', plotutils)

explainer.visualization(data=data, edge_mask=masks[0], top_k=3, plot_utils=plotutils)
```

![image](https://user-images.githubusercontent.com/8875555/184629534-7bb97f82-44db-4fdb-9088-e663646564cb.png)

**Comment by Oceanusity** [comment]
Thank you for your issue. I have updated the [visualization code](https://github.com/divelab/DIG/blob/91d7257ebd9537caf1ed27726e981be32be826bf/dig/xgraph/method/pgexplainer.py#L796), and add the hyper-parameter of `x`.

**Comment by matekenya** [comment]
Hello @Oceanusity, it appears this issue has not been resolved, I am still not able to produce the graph classification visualisation.
