### ISSUE TITLE
`MUTAG` dataset labelling

### ISSUE THREAD

**Issue by alirezadizaji** [divelab/DIG#145]
Hi thanks for sharing the dataset [here](https://github.com/divelab/DIG_storage/blob/main/xgraph/datasets/MUTAG.zip),
There are some graphs like 81st that has NO2 but are labeled as 1 (non-mutagen). Is there something that I'm missing?
thanks
![Figure_1111](https://user-images.githubusercontent.com/33565522/186725061-34265b7b-d718-4931-a199-7be614c64a83.png)

**Comment by alirezadizaji** [comment]
Also there are some graphs like 141st that has NO2 and labeled as minus one.
![Figure_11111](https://user-images.githubusercontent.com/33565522/186725516-c7d1bc81-c098-410b-91b2-c1d96a1067fb.png)

**Comment by Oceanusity** [comment]
Hello, refer to [GNNExplainer](https://arxiv.org/pdf/1903.03894.pdf) and [MUTAG paper](https://pubs.acs.org/doi/10.1021/jm00106a046), carbon ring as well as chemical groups NH2 and NO2 is the reason for mutagenic.

However, they exist in molecules with both label 1 and -1 in MUTAG. Therefore, I am also confused about whether these functional groups are the reasons for mutagenic proprety.

**Comment by alirezadizaji** [comment]
Yeah I am confused about this too.
