### ISSUE TITLE
Subgraphx mismatch number of nodes for `BA2Motifs` dataset

### ISSUE THREAD

**Issue by alirezadizaji** [divelab/DIG#146]
Hi,
I have tried subgraphx on ba2motif dataset to capture 50% of nodes, it mostly works well but sometimes it didn't like the following image.
![603_X](https://user-images.githubusercontent.com/33565522/186727546-3a99dcfe-e5e4-4715-8104-72df699b2c3e.png)
here is my subgraphx config:
`
SubgraphX(self.model, num_classes=2, device=..., 
                        explain_graph=True, reward_method='mc_l_shapley',
                        min_atoms=12, high2low=True, 
                        subgraph_building_method='split', verbose=True)
`

**Comment by alirezadizaji** [comment]
I have fixed it by replacing 'mc_shapley' with 'mc_l_shapley' for reward_method

**Comment by alirezadizaji** [comment]
Sorry the problem still remains with changing reward method

**Comment by Oceanusity** [comment]
Hello, you can refer to our new tutorial materials, and it provides example to visualize results on `ba_shapes` dataset.
https://github.com/divelab/DIG/blob/dig-stable/tutorials/KDD2022/xgraph_code_tutorial.ipynb
