### ISSUE TITLE
Support DGL

### ISSUE THREAD

**Issue by eddiezha** [divelab/DIG#148]
Hi, my GNN is trained on DGL, it seems your lib does not support this. 
Is it possible to add this feature? Or you mind providing a quick way to do it? 
Thanks. (Specifically for explainability.)
BTW, a mode general question, do these methods support Relational Graph Convolutional Network?

**Comment by Oceanusity** [comment]
Hello, currently the DIG is based on the `torch_geometric` and the explainability relies on the [MessagePassing](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/conv/message_passing.html#MessagePassing) class. It's a pity that the dig explainability can't be applied to dgl model directly.

One possible way is to transfer your dgl model into torch_geometric model. That's to say, write the model with the torch_geometric framework and then load the parameters from the dgl model. 

For the second question, I think some model-agnostic explainability method such as `SubgraphX` can be applied to the Relational Graph Convolutional Network.

**Comment by eddiezha** [comment]
Thanks, transfer to torch_geometric seems difficult, I am wondering if there is any quick way to transfer dig explainability to dgl? Thanks.

**Comment by eddiezha** [comment]
I think your implementation cannot be used for RGCN right? It does not include edge type.

**Comment by Oceanusity** [comment]
Yes, I think it is a hard work to transfer dig explainability to dgl, and current implementation is not for GNN considering edge features like `RGCN`.
