### ISSUE TITLE
Heterogeneous GNN 

### ISSUE THREAD

**Issue by yudizhangzyd** [divelab/DIG#149]
Hi does those explanation methods work for Heterogeneous GNN?
Suppose my edges have multiple types, will they be able to identify which type is more critical?
Thanks.

**Comment by Oceanusity** [comment]
Hello, currently the implemented explanation algorithms are applied on homogeneous graph. Therefore, it is a pity that they can't be applied to heterogeneous GNN without modification.

**Comment by yudizhangzyd** [comment]
Thanks, but the original methods (from the paper) can be used on hetero GNN?

**Comment by Oceanusity** [comment]
I am not sure whether these explainability methods will work or not since these methods are not designed for hetero GNN.
Welcome to provide some insights if you find papers showing these experiments.
