### ISSUE TITLE
Missing Explanation results on google drive

### ISSUE THREAD

**Issue by vasyl-haievyi** [divelab/DIG#150]
Hello,
There are no explanation results saved in [the folder](https://drive.google.com/drive/u/0/folders/1zNm9i1XvAMeZsmvzS1fyeIwpnaU8AkK7). At least folders for gcn explanations are empty when I open them using my google account.

**Comment by vasyl-haievyi** [comment]
Also, I would like to ask, how to get subgraphx results for different sparsity levels, as you presented in the graph explainability survey?

**Comment by Oceanusity** [comment]
Hello, thank you for pointing it out. I have uploaded the checkpoints and results to the directory. Many thanks.
For the different sparsity level of `SubgraphX` results, you can change the parameter `max_nodes` https://github.com/divelab/DIG/blob/dig-stable/dig/xgraph/method/subgraphx.py#L756

**Comment by vasyl-haievyi** [comment]
Thank you very much!
