### ISSUE TITLE
Standardized MAE Calculation

### ISSUE THREAD

**Issue by fmocking** [divelab/DIG#151]
Hello! I'm trying to reproduce the standardized MAE values reported in SphereNet paer. The values I'm getting are slightly off on QM9 and MD17 datasets. I was wondering if it is possible to clarify the calculation (with the std value used to calculate it). 

Thanks!

**Comment by limei0307** [comment]
Hi @fmocking, 

Thanks for your interest. We follow [DimeNet](https://arxiv.org/pdf/2003.03123.pdf) to compute the standard MAE (equation 10 and 11). The most important thing is computing the standard deviation. I computed the standard deviation by myself and found that the std.MAE and logMAE values are consistent with the DimeNet paper. 

[Here](https://docs.google.com/spreadsheets/d/18XsWNJ0ECwdzSr_Swciaai9bS0335rrnV8zON7S1OgE/edit?usp=sharing) are the computed standard deviation and steps to calculate std.MAE and logMAE. Please take a look and help us check it.

Thanks!
Limei Wang

**Comment by fmocking** [comment]
Hi @limei0307,

Thank you so much for sharing the file to calculate the values, it is really helpful. After comparing with the values I have for std dev., there is a slight difference between the values. I assumed the std dev. was calculated over the test set. Now I see that it is calculated over all datasets rather than train or test sets. Thanks again.

Best,
