### ISSUE TITLE
Tutorial for GNN Explainability--Code Example--problems

### ISSUE THREAD

**Issue by gongchenghua** [divelab/DIG#152]
[https://diveintographs.readthedocs.io/en/latest/tutorials/subgraphx.html](url)
Hi! when I follow the code example, I find that in step 2:
`def check_checkpoints(root='./'):
    if osp.exists(osp.join(root, 'checkpoints')):
        return
    url = ('https://github.com/divelab/DIG_storage/raw/main/xgraph/checkpoints.zip')
    path = download_url(url, root)
    extract_zip(path, root)
    os.unlink(path)
`
here download_url is not defined, so what should I do to solve the problems?

**Comment by Oceanusity** [comment]
I think you can try `from torch_geometric.data.download import download_url`.
