### ISSUE TITLE
Can't import SphereNet (version error)

### ISSUE THREAD

**Issue by sentinel8b** [divelab/DIG#156]
Hi, I've recently read your paper about SphereNet and it was impressive.
But I had a error when I tried import SphereNet with code below
```python
from dig.threedgraph.method import SphereNet
```
error message was like this. 
```
No module named 'torch_geometric.nn.acts'
```
I think it's because DIG library is not compatible with PyG = 2.1.0

Could you manage your project to support PyG = 2.1.0?
or let me know how to handle those error.

**Comment by sentinel8b** [comment]
my torch version is 1.12.1+cu113 and torch_geometric version is 2.1.0

**Comment by Mahmood-Kazemi** [comment]
Hi, I also faced this error yesterday! 
I think the best solution is to change a particular single line in these files:
dimenetpp.py - spherenet.py - comenet.py - pronet.py .

change 
`from torch_geometric.nn.acts import swish`
to
`from torch_geometric.nn.resolver import swish`

I'll create a pull request for it.

**Comment by sentinel8b** [comment]
As @Mahmood-Kazemi reported,
change
```
from torch_geometric.nn.acts import swish
```
to
```
from torch_geometric.nn.resolver import swish
```
fixed my problem.

**Comment by limei0307** [comment]
Thanks a lot for all your questions and contributions to keeping our package up to date! 
I also updated the code to define the swish function directly in the model file as shown [here](https://github.com/divelab/DIG/commit/7a39e3ba00d69aa6fb6ae267b7a2f74981000287) to make our method compatible with more versions of PyG.

DIG team
