### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by akhilesh2295** [divelab/DIG#158]
I ran the git installation procedure to install DIG on my local Windows machine. The dependency pyscf could not be found. On investigating further, I found the package is not supported on Windows. 

The console output of the installation is given below with the errors and my further efforts of installation using pip/conda.

(base) C:\WINDOWS\system32>conda activate DIG

(DIG) C:\WINDOWS\system32>cd DIG

(DIG) C:\Windows\System32\DIG>pip insall .
ERROR: unknown command "insall" - maybe you meant "install"

(DIG) C:\Windows\System32\DIG>pip install .
Processing c:\windows\system32\dig
  Preparing metadata (setup.py) ... done
Collecting scipy
  Downloading scipy-1.9.1-cp39-cp39-win_amd64.whl (38.6 MB)
     ---------------------------------------- 38.6/38.6 MB 12.8 MB/s eta 0:00:00
Collecting cilog
  Downloading cilog-1.2.3-py3-none-any.whl (14 kB)
Collecting typed-argument-parser==1.7.2
  Downloading typed-argument-parser-1.7.2.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Collecting captum==0.2.0
  Downloading captum-0.2.0-py3-none-any.whl (1.4 MB)
     ---------------------------------------- 1.4/1.4 MB 21.9 MB/s eta 0:00:00
Collecting munch
  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
Collecting gdown
  Downloading gdown-4.5.1.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting shap
  Downloading shap-0.41.0-cp39-cp39-win_amd64.whl (435 kB)
     ---------------------------------------- 435.6/435.6 kB 28.4 MB/s eta 0:00:00
Collecting IPython
  Downloading ipython-8.5.0-py3-none-any.whl (752 kB)
     ---------------------------------------- 752.0/752.0 kB 49.5 MB/s eta 0:00:00
Collecting tqdm
  Downloading tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
     ---------------------------------------- 78.5/78.5 kB ? eta 0:00:00
Collecting rdkit-pypi
  Downloading rdkit_pypi-2022.3.5-cp39-cp39-win_amd64.whl (27.8 MB)
     ---------------------------------------- 27.8/27.8 MB 14.5 MB/s eta 0:00:00
Collecting pandas
  Downloading pandas-1.5.0-cp39-cp39-win_amd64.whl (10.9 MB)
     ---------------------------------------- 10.9/10.9 MB 20.4 MB/s eta 0:00:00
Collecting sympy
  Downloading sympy-1.11.1-py3-none-any.whl (6.5 MB)
     ---------------------------------------- 6.5/6.5 MB 21.8 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement pyscf==1.7.6.post1 (from dive-into-graphs) (from versions: 1.4.0, 1.4.0.9, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0, 1.5.1, 1.5.3, 1.5.4, 1.5.5, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 2.0.0, 2.0.1, 2.1.0)
ERROR: No matching distribution found for pyscf==1.7.6.post1

(DIG) C:\Windows\System32\DIG>pip install pyscf
Collecting pyscf
  Downloading pyscf-2.1.0.tar.gz (8.5 MB)
     ---------------------------------------- 8.5/8.5 MB 12.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy!=1.16,!=1.17,>=1.13
  Downloading numpy-1.23.3-cp39-cp39-win_amd64.whl (14.7 MB)
     ---------------------------------------- 14.7/14.7 MB 19.3 MB/s eta 0:00:00
Collecting scipy!=1.5.0,!=1.5.1
  Using cached scipy-1.9.1-cp39-cp39-win_amd64.whl (38.6 MB)
Collecting h5py>=2.7
  Downloading h5py-3.7.0-cp39-cp39-win_amd64.whl (2.6 MB)
     ---------------------------------------- 2.6/2.6 MB 33.6 MB/s eta 0:00:00
Building wheels for collected packages: pyscf
  Building wheel for pyscf (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Configuring extensions
      cmake -SC:\Users\Akhilesh\AppData\Local\Temp\pip-install-cdh3vh42\pyscf_c44f599cd7784334b55a4937d49d1d4e\pyscf\lib -Bbuild\temp.win-amd64-cpython-39\Release
      error: command 'cmake' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyscf
  Running setup.py clean for pyscf
Failed to build pyscf
Installing collected packages: numpy, scipy, h5py, pyscf
  Running setup.py install for pyscf ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pyscf did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running install
      C:\Users\Akhilesh\anaconda3\envs\DIG\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      Configuring extensions
      cmake -SC:\Users\Akhilesh\AppData\Local\Temp\pip-install-cdh3vh42\pyscf_c44f599cd7784334b55a4937d49d1d4e\pyscf\lib -Bbuild\temp.win-amd64-cpython-39\Release
      error: command 'cmake' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyscf

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

(DIG) C:\Windows\System32\DIG>conda install -c pyscf pyscf
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyscf

Current channels:

  - https://conda.anaconda.org/pyscf/win-64
  - https://conda.anaconda.org/pyscf/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

(DIG) C:\Windows\System32\DIG>

**Comment by ycremar** [comment]
Thank you for raising the issue @akhilesh2295 !

@lyzustc : Can we remove the requirement of `pyscf` or the `post1` version requirement from `setup.py`? It is only required by ggraph3d but prevents the installation under Windows.

**Comment by lyzustc** [comment]
@ycremar `pyscf` cannot be removed because it is required for evaluation in ggraph3d, but post1 version requirement can be removed.

**Comment by lyzustc** [comment]
@akhilesh2295 I have updated the pyscf version to 1.7.6 in setup.py, could you please try git installation with new setup.py? Thanks!

**Comment by mengliu1998** [comment]
I am closing this issue since there is no ongoing discussion. Feel free to re-open it if the problem still exists.

**Comment by anders1123** [comment]
Sorry I still cannot install DIG on my windows device because the pyscf library does not support the Windows platform. Can you provide any useful suggestions

**Comment by sunyrain** [comment]
> Sorry I still cannot install DIG on my windows device because the pyscf library does not support the Windows platform. Can you provide any useful suggestions

Same Question
