### ISSUE TITLE
xgraph/PGExplainer edge mask values

### ISSUE THREAD

**Issue by neolifer** [divelab/DIG#16]
I find that the edge mask values in the pgexplainer implementation can be larger than 1 when i run the code on BA_shapes dataset. In the original paper and the official implementation the values are in (0, 1). Would this be a problem?
an example edge mask output:
ori_node_idx = 699
tensor([6.2408, 6.2408, 6.2408, 6.2408, 6.2408, 6.2408, 6.2408, 6.2408, 6.2408,
        6.2408, 7.1816, 7.1816, 5.8144, 5.4829, 5.3828, 5.8144, 5.2910, 5.1266,
        5.2910, 4.9597, 5.4829, 4.9597, 5.3828, 5.1266], device='cuda:0')

**Comment by Nate1874** [comment]
The absolute values of attribution scores are not important. We only care about the relatively importance. With simple normalizations, the values will be in [0,1] but the rankings remain the same. @Oceanusity any other comments?

**Comment by Oceanusity** [comment]
Thank you for your issue, it seems like I have not uploaded the newest PGExplainer code in the main branch, and I will update the code. Of course with the sigmoid normalization, the value will be in [0, 1].
In the torch_geometric package, there will be a default sigmoid() normalization function in the propagation method. Therefore, we don't need to normalize the edge mask. However, in the latest update in the main branch, I rewrite the propagation method and delete the original sigmoid() normalization. Therefore, a new sigmoid() normalization in PGExplainer is needed, and I will have updated the code.
