### ISSUE TITLE
'data_batch.batch' in SphereNet model， What does this mean and how do you get it?

### ISSUE THREAD

**Issue by flpan** [divelab/DIG#161]
in `https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/spherenet/spherenet.py`
In line 285:
    def forward(self, batch_data):
        z, pos, batch = batch_data.z, batch_data.pos, batch_data.batch

I know that 'z' represents' atom_type 'and 'pos' represents 3D coordinates. But I don't know how this `batch` was obtained. Could you please help me with it? I didn't find out how in the qm9/qm17 datasets.
Thank you very much!

**Comment by limei0307** [comment]
Hi @flpan,

We use  `DataLoader` in [PyG](https://github.com/pyg-team/pytorch_geometric) to obtain each batch of data. You can find the code in [run.py](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/run.py) ([line 53](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/run.py#L53) and [line 121](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/run.py#L121)).
We also provide [an example](https://github.com/divelab/DIG/blob/dig-stable/examples/threedgraph/threedgraph.ipynb) to train the model. Please let me know if you have further questions. Thanks!

Best

**Comment by flpan** [comment]
OK, thanks for your reply! I have some solutions. First, I use ` torch_ Geometric. data. Data ` Create data and then use ` torch_ Geometric. data. Dataloader ` for processing.
Best!
