### ISSUE TITLE
a leaf Variable that requires grad is being used in an in-place operation

### ISSUE THREAD

**Issue by SickleLeeks** [divelab/DIG#164]
When I execute rand_gen.py, I get this error: `RuntimeError: a leaf Variable that requires grad is being used in an in-place operation`.
and my dig version is 1.0.0, What should I do?

**Comment by mengliu1998** [comment]
Hi @SickleLeeks,

Could you give us a specific pointer of the error, like which code line are you referring to? Thanks!

**Comment by mengliu1998** [comment]
I am closing this issue since there is no further ongoing discussion. Feel free to re-open it in any case.
