### ISSUE TITLE
Evaluation script used in Comenet on OC20 

### ISSUE THREAD

**Issue by fmocking** [divelab/DIG#173]
Hi again. Thank you for the great work. How did you evaluate the trained model (including the ID, OOD Ads, OOD Cat, OOD Both subsets) on the validation set using the OCP framework on validation set? Is it possible to share commands/scripts used for this process?

Best regards,

**Comment by limei0307** [comment]
Hi @fmocking, to evaluate the model on the validation sets (ID, OOD Cat, OOD Ads, OOD both), you should 
1. update the validation dataset in this line, https://github.com/Open-Catalyst-Project/ocp/blob/main/configs/is2re/all/base.yml#L8, the default validation set is ID,
2. then use this line to test your performance, python main.py --mode predict --config-yml configs/is2re/all/comenet/comenet.yml --checkpoint checkpoints/[TIMESTAMP]/checkpoint.pt

Thanks
