### ISSUE TITLE
Found a naming error.

### ISSUE THREAD

**Issue by SaraiQX** [divelab/DIG#175]
Hi DIG team,
I just found a naming conflict: 
It is "Rand_Gen_Evaluator" in the line "from dig.ggraph.evaluation import RandGenEvaluator" of https://github.com/divelab/DIG/blob/dig-stable/examples/ggraph/JTVAE/rand_gen.ipynb, 

while it is "RandGenEvaluator" in the .../site-packages/dig/ggraph/method/JTVAE/__init__.py installed in my virtual env.

Best,
Sarai

**Comment by lyzustc** [comment]
Hi Sarai,

Thank you very much for pointing out this error! We have corrected it.

Best,

**Comment by SaraiQX** [comment]
No problem. Glad to help😄. Thank you for the amazing library!
