### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_geometric.nn.acts'

### ISSUE THREAD

**Issue by vict0rsch** [divelab/DIG#186]
I've seen [this fix](https://github.com/divelab/DIG/commit/575b9c10e71f6e1f82a8f95ca0027c49bda71afa) for SphereNet but somehow it did not make it through to other models. Could it be implemented for all models?

**Comment by vict0rsch** [comment]
Or 

```
try:
    from torch_geometric.nn.acts import swish
except ImportError:
    from torch_geometric.nn.resolver import swish
```

**Comment by limei0307** [comment]
Hi @vict0rsch, we have [fixed this for other models](https://github.com/divelab/DIG/commit/7a39e3ba00d69aa6fb6ae267b7a2f74981000287). Please let us know if you have any further questions.

**Comment by vict0rsch** [comment]
My bad, actually this is a matter of pip release, it works installing from source

```
pip uninstall dive-into-graphs
pip install git+https://github.com/divelab/DIG.git#egg=dive-into-graphs
```

**Comment by vict0rsch** [comment]
Do you have a release planned?

**Comment by mengliu1998** [comment]
Hi @vict0rsch, we recommend installing from the source to use this first. We will release a new version recently (around this weekend)!

**Comment by vict0rsch** [comment]
Ok thanks!!
