### ISSUE TITLE
where is ocpmodels in dig/threedgraph/method/comenet/ocp/comenet-ocp.py

### ISSUE THREAD

**Issue by cuitaoyong** [divelab/DIG#191]

**Comment by limei0307** [comment]
Hi @cuitaoyong, 

We use [the original OC20 framework](https://github.com/Open-Catalyst-Project/ocp) to train ComENet model. To run the code, please put files `comenet-ocp.py` and `utils.py` in a new directory `comenet` of `ocpmodels` directory, and put `comenet.yml` into the corresponding configs directory (e.g. https://github.com/Open-Catalyst-Project/ocp/tree/main/configs/is2re/all).

Please let us know if you have any further questions.

Best
