### ISSUE TITLE
The returned fidelity is NAN

### ISSUE THREAD

**Issue by TimelessXZY** [divelab/DIG#199]
I have upgraded my DIG version to 1.1.0 now. When I use the given explaining demo of GNNExplainer ( https://github.com/divelab/DIG/blob/dig-stable/examples/xgraph/gnnexplainer.ipynb ), the given dataset 'ba_shapes', the given model 'GIN' and the given checkpoint 'GIN_2l_best', the output fidelity result is NAN which is not in line with the given result of fidelity 0.4682. I have also tried model GCN, which had the same issue. 

After debugging, I found that the masked_pred and maskout_pred were somehow all NANs.

**Comment by CM-BF** [comment]
This is caused by the missing of sigmoid function before using the masks. I have fixed it and updated the repo. Please reopen and let me know if there are any further questions. :smile:
