### ISSUE TITLE
SphereNet initialize atomic types tensor

### ISSUE THREAD

**Issue by pearl-rabbit** [divelab/DIG#201]
@limei0307 Hello,I have a question about the initialization section.Why is the 'num_embedding' of the network([https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/spherenet/spherenet.py#L59](url)) 95？

The input atomic type is an integer, but if I want to input an atomic type with another meaning of an integer, how should I set this value? 
And if the input atomic type is encoded with one-hot,can I replace 'Embedding()' with another network?

**Comment by limei0307** [comment]
Hi @pearl-rabbit, sure, you can use other networks to encode the atomic type, for example, change the `Embedding` function to `one_hot` function.

95 is a commonly used default value in [some previous work](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/models/dimenet.py#L130). You can change it to other values based on your dataset. Usually, you can set it to the max integer value in your dataset.
