### ISSUE TITLE
Availability of Graphair code (learning fair graph representation via automated data augmentations)

### ISSUE THREAD

**Issue by nigelnnk** [divelab/DIG#204]
Hi there, I am interested in your paper "LEARNING FAIR GRAPH REPRESENTATIONS VIA AUTOMATED DATA AUGMENTATIONS". 

This paper introduced Graphair as a graph augmentation method for fairness problems. In your paper, the code repository link points to this repo, but I can't seem to find Graphair in the repo or in the documentation. 

Would you please let me know where this code for Graphair can be found? Thanks!

**Comment by xyonly** [comment]
I also did not find the code for this paper.

**Comment by msadegh97** [comment]
I wasn't able to find the code either.

**Comment by mengliu1998** [comment]
Hi @nigelnnk, @nodusk, @msadegh97,

The GraphAIR code is ready. See https://diveintographs.readthedocs.io/en/latest/fairgraph/method.html#graphair
