### ISSUE TITLE
Type of atoms

### ISSUE THREAD

**Issue by YanjingLiLi** [divelab/DIG#205]
I am wondering where I can find a detailed description of the atom types here in the `get_atom_pos` function in
`https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/dataset/FOLDdataset.py`:

N, CA, CB, _G/_G1, _D/_D1, _E/_E1, _Z, NH1

**Comment by limei0307** [comment]
Hi @YanjingLiLi, the [get_atom_pos function here](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/dataset/FOLDdataset.py#L54) only get the coordinates of atoms that are used to compute side chain torsion angles. Specifically, the atoms for side chain torsion angle computation are listed in [Table 7 of our paper](https://openreview.net/forum?id=9X-hgLDLYkQ).
`N, CA, CB, _G/_G1, _D/_D1, _E/_E1, _Z, NH1`: `A` means alpha, `B` means beta, `G` means gamma, `D` means delta, `E` means epsilon, `Z` means zeta, and `H` means eta.

Thanks.

**Comment by YanjingLiLi** [comment]
In your code, you have `pos_n, pos_ca, pos_c, pos_cb`, what is `c` here, if `ca` is carbon alpha, `cb` is carbon beta?

**Comment by limei0307** [comment]
Yes. `c` means carbon, `n` means nitrogen, and `o` means oxygen.

**Comment by YanjingLiLi** [comment]
Thanks! But I am wondering what is `pos_c` mean here since it doesn't have any index. (`pos_ca` is for alpha carbon, `pos_cb` is for beta carbon)

**Comment by limei0307** [comment]
Hi, `pos_c` is another carbon atom in an amino acid (the `c` in the `-COOH` group).

**Comment by YanjingLiLi** [comment]
Get it. Thanks.
