### ISSUE TITLE
How do I visualize molecular 3D graphs of a dataset (QM9)?

### ISSUE THREAD

**Issue by DongfangYu-Bruce** [divelab/DIG#212]

**Comment by DongfangYu-Bruce** [comment]
with ShpereNet

**Comment by limei0307** [comment]
Hi @DongfangYu-Bruce,

Thanks for your interest in our work!

To visualize a molecule in QM9, I think you can download the original QM9 from here (https://figshare.com/collections/Quantum_chemistry_structures_and_properties_of_134_kilo_molecules/978904). For each molecule, there is a .xyz file, and you can use a tool like https://www.rcsb.org/3d-view/ to visualize it.

Best,
