### ISSUE TITLE
Graphair mini-batch version

### ISSUE THREAD

**Issue by ZzoomD** [divelab/DIG#215]
Graphair is a great work and is definitely worth learning from. Could you please share the mini-batch version of Graphair? Hope to get your reply, thank you!

**Comment by hongyiling** [comment]
We use GraphSAINT(https://github.com/GraphSAINT/GraphSAINT) to perform mini-batch training. You can use their code to sample a subgraph for each training step.  Since GraphSAINT uses a different license from DIG, including their code in our library would be inappropriate.
