### ISSUE TITLE
Solution when alpha carbon coordinate is missing

### ISSUE THREAD

**Issue by YanjingLiLi** [divelab/DIG#221]
Hi, how do you handle the situation when the coordinate for alpha carbon in the dataset is missing?

**Comment by limei0307** [comment]
Hi @YanjingLiLi, if I remember correctly, we haven't met this situation. 
For [FoldDataset](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/dataset/FOLDdataset.py#L78) and [ECDataset](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/dataset/ECdataset.py#L78), we start from the processed data [here](https://github.com/phermosilla/IEConv_proteins#download-the-preprocessed-datasets). Some coordinates for N and C are missing, and we set the position of C and N as the position of CA.

For your situation, I guess we can drop these residues. But I am not sure whether this is the solution used actually by biologists.

Thanks.
