### ISSUE TITLE
Query about GraphAug

### ISSUE THREAD

**Issue by zheng-awei** [divelab/DIG#223]
Hello! 
It Seems like the code here miss something. I think we should pass the value: args.reward_gen_state_path to conf[REWARD_GEN_STATE_PATH].

![image](https://github.com/divelab/DIG/assets/74601223/e0ef40e1-5a49-4adc-9c60-4a25e01184bc)

**Comment by lyzustc** [comment]
Hi zheng-awei,

Thanks for your information! We have fixed this issue in GraphAug codes.
