### ISSUE TITLE
Codes and scripts for ProNet

### ISSUE THREAD

**Issue by twopin** [divelab/DIG#227]
Hi, nice work of the library! I'm wondering if there are tutorials or main scripts for ProNet? I notice there are data loading class of Folddataset as well as the main network architecture of ProNet. However, the data encoding part and the training scripts are not releasing yet. Thank you so much.

**Comment by limei0307** [comment]
Hi @twopin, thanks for your interest in our work! [Here](https://github.com/divelab/DIG/blob/dig-stable/examples/threedgraph/run_ProNet.py) is the link to the running script of ProNet. Please let us know if you have further questions. Thanks.

**Comment by zpengmei** [comment]
Hi, thanks for the great work for protein tasks. I am also interested in using pronet but it seems the scripts for running atom3d tasks are missing too? Would you mind releasing those scripts to reproduce the results in the paper? Much appreciated!
