### ISSUE TITLE
Why it is allowed to have overlap between traning and valid & test sensitive labels in Graphair?

### ISSUE THREAD

**Issue by qslim** [divelab/DIG#229]
It seems all test set sensitive labels are used in training as follows.
https://github.com/divelab/DIG/blob/69c3e7e20c7c8c537ec615bc5c35167482d64b21/dig/fairgraph/dataset/fairgraph_dataset.py#L115C19-L115C19

However, I found several other codes that remove the overlap part like this "idx_sens_train = list(sens_idx - set(idx_val) - set(idx_test))". Why it doesn't need to do so here?

Anyway, I'm not familiar with the dataset split in fair graph learning and would appreciate any reference about this part.

**Comment by hongyiling** [comment]
In our work, we focus on learning fair graph representations, and we are not doing supervised learning as some other works. In our first step, we aim to learn the fair graph representations. In this step, we assume all the information except the labels for the downstream tasks is known. In other words, during training Graphair, the sensitive attributes are known. In our second step, we use the learned representation to do the downstream tasks. In this step, we will train a simple model (ex. MLP) to do the downstream tasks using our learned representations. To do this, we will split the task labels into train/val/test for the simple model (ex. MLP) to test our learned representations.
