### ISSUE TITLE
Code for 3d graph reproduction of results on MD17 

### ISSUE THREAD

**Issue by octavian-ganea** [divelab/DIG#23]
Thanks for this very useful library. Is it please possible to add some code similar to benchmarks/threedgraph/threedgraph.ipynb for running Spherenet on MD17 together with the necessary parameters to reproduce the results from the paper ? Thanks!

**Comment by limei0307** [comment]
Hi, I will add more benchmark code. To run SphereNet on MD17, we need to set the parameter energy_and_force in SphereNet() and run() to be True. If set to True, we will predict the energy and take the negative of the derivative of the energy with respect to the atomic positions as predicted forces. (default: False). 
The parameters are listed in the appendix of our paper https://arxiv.org/pdf/2102.05013.pdf. Thanks.
