### ISSUE TITLE
Adding a new node feature to a Spherenet model

### ISSUE THREAD

**Issue by LeonardoBarneschi** [divelab/DIG#234]
Dear developers,

I am training a Spherenet model to predict a molecular property. I was wondering if, aside from the atomic number ( as far as I understand ), it would be possible to include extra node features in the network. Could you eventually provide a minimal example? 

Kindest Regards,
L.

**Comment by limei0307** [comment]
Hi @LeonardoBarneschi, 

Thanks for your interest in our work. You can find the example code here [(new commit)](https://github.com/divelab/DIG/commit/1d35357d57ac2d5e35672411f295f81ed471b927) [(code)](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/spherenet/spherenet.py).

To include extra node features, you can provide extra node features **node_feature** to the model, as shown [here](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/spherenet/spherenet.py#L299).

When calling the SphereNet model, you need to set `use_extra_node_feature=True` and `extra_node_feature_dim=your_dim`. 

For example, you can use
`model = SphereNet(energy_and_force=False, cutoff=5.0, num_layers=4, 
        hidden_channels=128, out_channels=1, int_emb_size=64, 
        basis_emb_size_dist=8, basis_emb_size_angle=8, basis_emb_size_torsion=8, out_emb_channels=256, 
        num_spherical=3, num_radial=6, envelope_exponent=5, 
        num_before_skip=1, num_after_skip=2, num_output_layers=3, use_node_features=True, use_extra_node_feature=True, extra_node_feature_dim=3
        )`

Let us know if you have other questions. Thanks.

**Comment by LeonardoBarneschi** [comment]
Hi @limei0307,

This is just amazing! Thank you very much, I really appreciate it. 

Kindest Regards,
Leonardo
