### ISSUE TITLE
Run GNNExplainer

### ISSUE THREAD

**Issue by paulamartingonzalez** [divelab/DIG#24]
I am trying to run the GNN Explainer code. Although I have used the install.batch to generate the conda environment, I am having issues with the packages. Namely with tap (in the line "from tap import Tap") . I tried installing it myself and I can import tap but doesn't seem to find anything called Tap on it. Could you guide me here please?

Also, I was going through the example and I was wondering which settings should I change to run it on the graph level predictions. Is there an example for that? And, is it possible to get the feature importances and the important subgraphs? I didn't see any outputs in the explain functions.

Thanks in advance!

**Comment by Oceanusity** [comment]
Hi, thank you for your issue. 

First, the Tap package can be installed by the command `pip install typed-argument-parser==1.5.4`. 

Second, if you want to explain the graph level predictions, you can simply set the explain_graph attribute to True  `explain_graph=True`. In addition, GNNExplainer returns the importance score for each edge, and you can find it as the return value `edge_masks`  in the forward function of GNNExplainer. By the way, `edge_masks` is a list, where `edge_masks[0]` is the edge_mask for the class 0, and `edge_mask[1]` is the edge_mask for class 1.

**Comment by Oceanusity** [comment]
One more thing, there will be a default sigmoid function for the edge_masks value in the propagation method in the `torch_geometric.nn.MessagePassing` class. Thus, the `edge_mask` value will be in the range 0-1 after the sigmoid function, and the return value `edge_masks` in the forward function doesn't in the range 0-1.

**Comment by paulamartingonzalez** [comment]
Many thanks for your help! I have everything installed now! Nevertheless, I am encountering a few issues when running the code:

- if I run  `python -m benchmark.kernel.pipeline --task explain --model_name [GCN_2l/GCN_3l/GIN_2l/GIN_3l] --dataset_name [ba_shape/ba_lrp/tox21/clintox] --target_idx [0/2] --explainer GNNExplainer --sparsity [0.5/...]` from the console, I get the error: `-m: error: argument --target_idx: invalid int value: '[0/2]'`
- If I run `python -m benchmark.kernel.pipeline --task explain --model_name GCN_3l --dataset_name clintox --target_idx 0 --explainer GNNExplainer --sparsity 0.5 --debug --vis --nolabel` also on the console, I get the error: `TypeError: draw_networkx_nodes() got an unexpected keyword argument 'num_nodes'
- Anf, when trying to run the script /benchmark/pipeline.py on spyder, I get the error `AssertionError: Explaining on multi tasks is meaningless.` that comes from benchmark/data/dataset.py
Any hint on how to make this work?

I'd like to explore the examples before I get to try my own data, so I might followup on the explanation bit and edge masks once I manage to get the code running. Thanks again!
`

**Comment by Oceanusity** [comment]
Hi, I have the following suggestions for the issues.

* Please select one from the optional selections for parameters.
* Please follow issue #12.
* I am not sure about this problem. If it happens again with the others fixed, feel free to give me more details.

**Comment by paulamartingonzalez** [comment]
Many thanks again! Following that issue, the second point works well.

Now, when I try to run: python -m benchmark.kernel.pipeline --task explain --model_name GCN_3l --dataset_name ba_shape --target_idx 2 --explainer GNNExplainer --sparsity 0.5 I get File "/home/martin09/DIG/dig/xgraph/GNNExplainer/benchmark/models/model_manager.py", line 45, in config_model
    print(f'#E#Checkpoint not found at {os.path.abspath(args.test_ckpt)}')
This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629395347/work/torch/csrc/utils/python_arg_parser.cpp:766.)

I tried reinstalling everything from scratch to check if that was the issue, but it persisted. Do you have any hint of what may be happening?

**Comment by paulamartingonzalez** [comment]
Small update: using `python -m benchmark.kernel.pipeline --task explain --model_name GCN_3l --dataset_name tox21 --target_idx 2 --explainer GNNExplainer --sparsity 0.3 --vis` it worked, which makes me think that perhaps the model for the combination above did not exist.

I think I will close the issue, I will be exploring the code the next couple of days and I might reopen it with more questions. 😃 Thanks!

**Comment by paulamartingonzalez** [comment]
Hi again! I am afraid I need to reopen the issue! 

On Friday, I was able to successfully run the code from the command line using `python -m benchmark.kernel.pipeline --task explain --model_name GCN_3l --dataset_name tox21 --target_idx 2 --explainer GNNExplainer --sparsity 0.3 --vis`.

I would like to explore a bit the code and understand the settings to make it run on my own dataset and models. For that, I have generated a Jupyter notebook on my local GNNExplainer directory where I am trying to make the commands from "pipeline.py" work. I think there is a problem with the arguments not being there and I am not very sure how to pass them in this setting. Could you help, please?

The error I get is "AssertionError: Explaining on multi tasks is meaningless." but I think it comes because I can't set target_idx argument to 2 as in the command line above. Thanks in advance!

**Comment by paulamartingonzalez** [comment]
I am exploring the code on TOX21 dataset and I would like to understand a bit better the outputs (both the edge masks and the features masks). For the edge masks, is it the masks variable in sample_explain the one I should be looking at? For the feature masks, I don't really know where to find them. Would you mind pointing me? Is there a genera feature mask for all the cohort? or is it one per graph?

I would like to get something as Figure 5 in GNNExplainer paper: [https://arxiv.org/pdf/1903.03894.pdf](url)

<img width="960" alt="Screenshot 2021-05-24 at 17 15 31" src="https://user-images.githubusercontent.com/45625166/119368786-b95d4f00-bcb3-11eb-9d4d-1fe83268d9e9.png">

**Comment by Oceanusity** [comment]
For the GNNExplainer class, you can extract the node mask and edge mask from the class attribute `self.node_feat_mask` and `self.edge_mask`. Please take `mask_features=True` to explain the importance of node features.
 
For the figure, GNNExplainer provides the visualization as shown in README.md. It's not the same as the GNNExplainer paper, but I think it can help you with the figure to some extend.
