### ISSUE TITLE
Run DIG/benchmarks/xgraph/gnnexplainer.ipynb

### ISSUE THREAD

**Issue by chao92** [divelab/DIG#25]
Hi,
When I try to run the gnnexplainer.ipynb, error comes as: 
from inspect import isclass
----> 9 import dig.xgraph.models.models as models
     10 import torch

AttributeError: module 'dig.xgraph' has no attribute 'models'

Any suggestions? Thanks

**Comment by liyuntong9** [comment]
Whether I install dig from pip or from source, no error was reported during the installation. 
However, when I run the gnnexplainer.ipynb, I have the same problem:
AttributeError: module 'dig.xgraph' has no attribute 'models'

I found the module 'dig.xgraph' only has the following attributes:
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'dataset', 'utils']

How can I solve it?

**Comment by chao92** [comment]
Everything works after I  reinstalled with replacing python from 3.6 to 3.7. It's weird. I could attach my yml file for your information.

`name: DIG
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - boost=1.74.0=py37h6dcda5c_3
  - boost-cpp=1.74.0=h312852a_4
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2020.12.5=ha878542_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2020.12.5=py37h89c1867_1
  - cycler=0.10.0=py_2
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h0b5b191_1005
  - greenlet=1.1.0=py37hcd2ae1e_0
  - icu=68.1=h58526e2_0
  - importlib-metadata=4.0.1=py37h89c1867_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py37h2527ec5_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libdeflate=1.7=h7f98852_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libglib=2.68.2=h3e27bee_0
  - libgomp=9.3.0=h2828fa1_19
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=9_openblas
  - libopenblas=0.3.15=pthreads_h8fe5266_1
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.12=h72842e0_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - matplotlib-base=3.4.2=py37hdd32ed1_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.20.3=py37h038b26d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h7f98852_0
  - pcre=8.44=he1b5a44_0
  - pillow=8.2.0=py37h4600e1f_1
  - pip=21.1.1=py37h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycairo=1.20.0=py37hfff247e_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.7.10=hdb3f193_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd8ed1ab_0
  - rdkit=2021.03.2=py37haf5a968_0
  - readline=8.1=h27cfd23_0
  - reportlab=3.5.67=py37h69800bb_0
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=1.4.15=py37h5e8e339_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py37h5e8e339_1
  - typing_extensions=3.7.4.3=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.1=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - argon2-cffi==20.1.0
    - ase==3.21.1
    - async-generator==1.10
    - attrs==21.2.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cached-property==1.5.2
    - captum==0.2.0
    - cffi==1.14.5
    - chardet==4.0.0
    - cilog==1.2.0
    - cloudpickle==1.6.0
    - decorator==4.4.2
    - defusedxml==0.7.1
    - dive-into-graphs==0.0.4
    - entrypoints==0.3
    - et-xmlfile==1.1.0
    - future==0.18.2
    - googledrivedownloader==0.4
    - h5py==3.2.1
    - idna==2.10
    - ipykernel==5.5.5
    - ipython==7.23.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - isodate==0.6.0
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.12
    - jupyter-console==6.4.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - llvmlite==0.36.0
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - mypy-extensions==0.4.3
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.5.1
    - notebook==6.4.0
    - numba==0.53.1
    - openpyxl==3.0.7
    - packaging==20.9
    - pandas==1.2.4
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.10.1
    - prompt-toolkit==3.0.18
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pygments==2.9.0
    - pyrsistent==0.17.3
    - python-louvain==0.15
    - pyzmq==22.0.3
    - qtconsole==5.1.0
    - qtpy==1.9.0
    - rdflib==5.0.0
    - requests==2.25.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - send2trash==1.5.0
    - shap==0.39.0
    - slicer==0.0.7
    - tabulate==0.8.9
    - terminado==0.10.0
    - testpath==0.5.0
    - threadpoolctl==2.1.0
    - torch==1.6.0+cpu
    - torch-cluster==1.5.9
    - torch-geometric==1.7.0
    - torch-scatter==2.0.6
    - torch-sparse==0.6.9
    - torch-spline-conv==1.2.1
    - torchvision==0.7.0+cpu
    - tqdm==4.61.0
    - traitlets==5.0.5
    - typed-argument-parser==1.5.4
    - typing-inspect==0.6.0
    - urllib3==1.26.4
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
prefix: /home/chao/.conda/envs/DIG
`

**Comment by liyuntong9** [comment]
I'll try it. Thanks for your help!
