### ISSUE TITLE
edge_mask operation on GNNExplainer

### ISSUE THREAD

**Issue by chao92** [divelab/DIG#26]
Hi,

When I read the GNNExplainer source code, I have a little confused about how to edge_mask was applied to the forward step.

For instance, considering the demo: https://github.com/divelab/DIG/blob/dig/benchmarks/xgraph/gnnexplainer.ipynb. I do found that we call the model **GCN_2l** and the **gnn_explainer_alg** also optimized the loss function including both feature mask and edge mask. It seems that the code did not use the class GCN_2l_mask which directly using of the edge_mask.

Thank you so much for your time.

Best,
Chao

**Comment by Oceanusity** [comment]
Hi, thank you for your issue.

In the **GCN_2l**, the edge_mask is used in the propagation method of the class **nn.MessagePassing**, which is the parent class of *GCN_Conv*. For the **GCN_2l_mask**, I rewrite the propagation method and delete the sigmoid function after edge_mask, and this model is specially used in PGExplainer.

**Comment by chao92** [comment]
Got it, thank you so much for your help.
