### ISSUE TITLE
Is that a typo in subgraphX ?

### ISSUE THREAD

**Issue by DDigimon** [divelab/DIG#31]
in line 683 of subgraphx.py:             " related_preds.append({'masked': maskout_score,"
Maybe "related_preds.append({'maskout': maskout_score,"

**Comment by Oceanusity** [comment]
Thank you for your report, and I have fixed the [typo](https://github.com/divelab/DIG/blob/f6309b9d4a5e06420764a426c6be10c38cc6a03f/dig/xgraph/method/subgraphx.py#L683) now.
