### ISSUE TITLE
Explaining a batch of graphs in SubgraphX

### ISSUE THREAD

**Issue by zaixizhang** [divelab/DIG#32]
Hi,

I read the paper "On Explainability of Graph Neural Networks via Subgraph Explorations" and find your work quite exciting. I take a look at your codes and find subgraphx can only explain graphs one by one. Is it possible to send a batch of graphs to subgraphx so that the explanation can speed up?

**Comment by Oceanusity** [comment]
Thank you for your issue.

It's quite an interesting idea to use Subgraphx for a batch of graphs. I think the biggest problem is how to build different search trees for a batch of graphs parallelly. 

If you have some ideas about how to realize or willing to implement, it will be a great job. And welcome to contribute to our code.
