### ISSUE TITLE
[QUESTION]: XGNN missing from dig branch

### ISSUE THREAD

**Issue by titaniumrain** [divelab/DIG#36]
Hey folks, 

Quick question regarding XGNN. It seems missing from dig branch (but available in main branch). Any specific reasons behind its (temporary) unavailability?

Cheer,

V

**Comment by Nate1874** [comment]
It will be available in main branch for now. Since XGNN is very different from instance-level explanations, it cannot be easily modularized as others. We do not have a perfect solution yet so we will leave it in the main branch for now.

**Comment by titaniumrain** [comment]
Thanks @Nate1874 for the explanation. Truly appreciated!
