### ISSUE TITLE
SubgraphX

### ISSUE THREAD

**Issue by HyunjuKang** [divelab/DIG#37]
Hello, 

I would like to ask you for detailed info, especially on how to identify the subgraph with the following questions:

1. How can we select N0 as initialization which you define the root of search tree? 
   N_i means node, so Figure1 in the paper of subgraphX, which node is the N0 as initialization in root?
   
2. It is mentioned that h(N_i) denotes the associated subgraph of tree node N_i. I would like to know how you define "associated subgraph" and in Figure1, do you describe h(N_i)?

3. To obtain concrete understanding notation S, in Figure1 S as the possible coalition set of players is (node1), (node6) respectively, and (node 1 and 6). But in pseudo-code of Algorithms1, S_l is the leaf set so that the Leaves graph (which node list is equal to [ 2, 4] and edge list is equal to [(2, 4)]) belongs to S_l.

Thank you !

**Comment by Nate1874** [comment]
Hello,

Thanks for your questions.

1. The initialization of root is the original computation graph. For graph classification tasks, it will be the whole graph. For node classification task, it will be the $L$-hop subgraph where the target node is the center.
2. As we can see in Figure 1, the path is a 5 node path from the root to the leave. Each node is a tree node of monte carlo search tree. Then in each tree node, we have an associated subgraph, which is obtained by node pruning from its parent tree node. 
3. Sorry for the confusion. $S$ is the possible coalition set and $S_l$ is the leaf set of the MC search tree. These two notations are different.  For Figure 1, yes, the $S$ will be {node1}, {node6}, {node1,node6}, respectively. And $S_l$ is empty in the begining, after this search path, it become the tree node whose associated subgraph (node2 node4 connected).

**Comment by HyunjuKang** [comment]
Thank you for the answers.
I also have another questions following:

1.
To make N notation clear, normally in graph theory node means a single node or a vertex but in subgraphX, Does N_0 or N_i(you express tree node) or curNode means a kind of subgraph? not a single node?

2.
If it does, in pseudo-code of Algorithms 1, 
when curNode = N_0 then, possible actions(a_j) of h(curNode) can be all of each edge in input graph? 
+ a number of a_j can be more than one?

3.
in pseudo code, "Compute R(curNode, a_j) = Score(f(.), G, G_j)",
How can we obtain "a_j" from the contribution score of G_j?
(suppose a_j could be the Edge(G)- Edge(G_j), just I want to make sure of it to connect a_j and the score)

I hope just trying to understanding fully doesn't make you feel too much bothersome.
I appreciate your effort for the paper also responding to these answers!

Thank you

**Comment by Nate1874** [comment]
Hi, thanks for you question. 

First, there are two different types of nodes: MC tree node  and graph node. Each MC tree node is associated with a subgraph. In the paper, $N_i$ means the MC tree node. 

2. $N_0$ is the root of the search tree, which is associated with the whole computation subgraph, say $G_0$. Then possible actions(a_j) mean different pruning actions.  An action a_0 will lead to a child node of $N_0$ and let's denote its associated subgraph as $G_1$. Then $G_1$ is a subgraph obtained from $G_0$ with action a_0.

3. The reward R(curNode, a_j) is obtained by computing the Shapley score for the obtained subgraph G_j, which is shown in Algorithm 2.
