### ISSUE TITLE
device mismtach in GraphAF benchmark

### ISSUE THREAD

**Issue by GilgameshD** [divelab/DIG#38]
Thanks for providing this amazing work. 

When I run the GraphAF benchmark, I encounter this error:

RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu

After checking the code, I find that in line 32 of graphflow.py, the model MaskedGraphAF still uses CPU. I can remove the above error by adding:

self.flow_core = self.flow_core.cuda()

Just want to make sure whether this is a bug. Thanks.

**Comment by YKQ98** [comment]
Many thanks for your intrest!
Can you tell me which benchmark file are you running? Did you run the benchmark according to the readme guidence?
I re-runed the random generation code and didn't find this error info.

**Comment by GilgameshD** [comment]
Thanks for your reply. I use the following command:

CUDA_VISIBLE_DEVICES=0 python run_rand_gen.py --train --data=qm9 

But the weird thing is I can't reproduce the error either. Maybe there was something wrong in my environment. Thanks
