### ISSUE TITLE
pgexplainer.ipynb/subgraphx.ipynb - UnboundLocalError: local variable 'x' referenced before assignment

### ISSUE THREAD

**Issue by GiuseppeSerra93** [divelab/DIG#41]
from dig.xgraph.method import PGExplainer
    explainer = PGExplainer(model, in_channels=900, device=device, explain_graph=False)  
    explainer.train_explanation_network(splitted_dataset)  
    torch.save(explainer.state_dict(), 'tmp.pt')  
    state_dict = torch.load('tmp.pt')  
    explainer.load_state_dict(state_dict)

When running the block of code above, it returns the following error:

    ---------------------------------------------------------------------------
    UnboundLocalError                         Traceback (most recent call last)
    /tmp/ipykernel_1299148/3789046373.py in <module>
          2 explainer = PGExplainer(model, in_channels=900, device=device, explain_graph=False)
          3 
    ----> 4 explainer.train_explanation_network(splitted_dataset)
          5 torch.save(explainer.state_dict(), 'tmp.pt')
          6 state_dict = torch.load('tmp.pt')
    
    ~/anaconda3/envs/xai_conda_env/lib/python3.8/site-packages/dig/xgraph/method/pgexplainer.py in train_explanation_network(self, dataset)
        594                     x, edge_index, y, subset, _ = \
        595                         self.get_subgraph(node_idx=node_idx, x=data.x, edge_index=data.edge_index, y=data.y)
    --> 596                     logits = self.model(data.x, data.edge_index)
        597                     emb = self.model.get_emb(data.x, data.edge_index)
        598 
    
    ~/anaconda3/envs/xai_conda_env/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
       1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
       1050                 or _global_forward_hooks or _global_forward_pre_hooks):
    -> 1051             return forward_call(*input, **kwargs)
       1052         # Do not call functions when jit is used
       1053         full_backward_hooks, non_full_backward_hooks = [], []
    
    ~/anaconda3/envs/xai_conda_env/lib/python3.8/site-packages/dig/xgraph/models/models.py in forward(self, *args, **kwargs)
        270         :return:
        271         """
    --> 272         x, edge_index, batch = self.arguments_read(*args, **kwargs)
        273 
        274 
    
    ~/anaconda3/envs/xai_conda_env/lib/python3.8/site-packages/dig/xgraph/models/models.py in arguments_read(self, *args, **kwargs)
         42             elif len(args) == 2:
         43                 x, edge_index, batch = args[0], args[1], \
    ---> 44                                        torch.zeros(args[0].shape[0], dtype=torch.int64, device=x.device)
         45             elif len(args) == 3:
         46                 x, edge_index, batch = args[0], args[1], args[2]
    
    UnboundLocalError: local variable 'x' referenced before assignment

A similar error occurs with SubgraphX, but not with GNNExplainer. What is the problem?

**Comment by Oceanusity** [comment]
I have fixed this problem in #27, but we haven't released a new package yet. It'll be solved if you use the newest code in the DIG repo.

**Comment by Oceanusity** [comment]
We have released the newest package, please update.
