### ISSUE TITLE
If XGNN model will be added?

### ISSUE THREAD

**Issue by Yu-Fangxu** [divelab/DIG#45]
Thanks for this great project.
I notice that XGNN and this project are both your team's work, I wonder if you will add XGNN to this project recently?
Thanks!

**Comment by mengliu1998** [comment]
Thank you for your interest.

The code of XGNN is available in the "main" branch (https://github.com/divelab/DIG/tree/main/dig/xgraph/XGNN). Since XGNN is very different from instance-level explanations, it cannot be easily modularized as an API in DIG library.
