### ISSUE TITLE
fidelity score is negative in PGExplainer on BA-shapes

### ISSUE THREAD

**Issue by wtl0822** [divelab/DIG#47]
I run your program `xgraph/PGExplainer` on BA-shapes dataset using command `python pipeline.py --dataset_name BA_shapes --random_split True --latent_dim 20 20 20 --concate True --adj_normlize False --emb_normlize True` provided in scripts.sh. However, I get negative fidelity score -0.0706 when I set top_k as 6 because it is the number edge in motifs as paper illustrated:

`fetch network parameters from the saved files
training time is 0.007172066951170564s 
100%|████████████████████████████████████████████████| 42/42 [00:06<00:00,  6.76it/s]
fidelity score: -0.0706, sparsity score: 0.6932`

Secondly, when I add metric 'auc' under the guidance of official code of the paper, I get 0.5348. But the result reported in paper is 0.963, and I can get higher results when I run official code of the paper.

Why is that?

**Comment by Oceanusity** [comment]
Thank you for your issue. 

The fidelity here should not be negative, and I will try to figure it out.

For the 'auc' metric, the gcn model parameters provided in the official repo are different from those provided here. For models with different parameters, they might focus on different motifs and result in different explanation results.

**Comment by Oceanusity** [comment]
Hello, I have updated the pgexplainer code in the main branch, and fix the negative fidelity problem.

**Comment by wtl0822** [comment]
Hello, thanks for your early reply. I'm happy to hear that.
