### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by yyou1996** [divelab/DIG#5]
Thanks for your great work.

In https://github.com/divelab/DIG/blob/main/dig/sslgraph/example_mvgrl.ipynb line 2, `from sslgraph.eval_graph import EvalUnsupevised` should be `from sslgraph.utils.eval_graph import EvalUnsupevised`. Feel free to close it upon correction.

**Comment by ycremar** [comment]
Hi, thanks for letting us know. The typo has been corrected.
