### ISSUE TITLE
AttributeError: 'GCNConv' object has no attribute 'weight when I am running subgraphx.ipynb

### ISSUE THREAD

**Issue by Zha0nin9-Yu** [divelab/DIG#54]
Hi,
I got an AttributeError when I am running subgraphx.ipynb.
Could you help me with that?

**Comment by Oceanusity** [comment]
It seems like newest `torch_geometric` with version over 2.0.0 uses [`lin`](https://github.com/pyg-team/pytorch_geometric/blob/7c50f3cab69dc04d4cf4afffa9f422950261196f/torch_geometric/nn/conv/gcn_conv.py#L138) in the `GCN_Conv`.  However, in the pytorch_geometric older than 2.0.0 such as 1.7.2 uses [`weights`](https://github.com/pyg-team/pytorch_geometric/blob/5455b528d58e7d5b57f0046313065c160c4d4caa/torch_geometric/nn/conv/gcn_conv.py#L137). It will result in this conflict. Therefore, I recommend you to install `torch_geometric` between 1.6.0 and 1.7.2. Moreover, our datasets API don't support all the API in the `torch_geometric` over 2.0.0 now.

**Comment by Zha0nin9-Yu** [comment]
Could you tell me how can I install torch_geometric 1.7.2?
Following the instruction on the official website, I can only install the latest version.

**Comment by Oceanusity** [comment]
Please follow the official installation [guideline](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#installation-via-pip-wheels). Then replace the line `pip install torch_geometric` with `pip install torch_geometric==1.7.2`.

**Comment by Zha0nin9-Yu** [comment]
I have installed torch_geometric==1.7.2 but I got an error that ModuleNotFoundError: No module named 'torch_geometric.data.storage'.
Do you have any suggestions?

**Comment by Oceanusity** [comment]
How about `1.6.0`?

**Comment by Zha0nin9-Yu** [comment]
I can run the program now. But only under cuda 10.2, not 11.1.
Thank you for your help.

**Comment by HMY626** [comment]
Is there any way to install torch_geometric==1.7.2 on a cuda11.1 system, because the cuda version on the server cannot be changed.

**Comment by Oceanusity** [comment]
Please follow the official installation [guideline](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#installation-via-pip-wheels).

**Comment by notechen** [comment]
> I have installed torch_geometric==1.7.2 but I got an error that ModuleNotFoundError: No module named 'torch_geometric.data.storage'. Do you have any suggestions?

I have the same problem.
Can you tell me how you solved it？

**Comment by Oceanusity** [comment]
How about remove the processed data in the `processed` directory?

**Comment by notechen** [comment]
thank you
I'll give it a try

**Comment by bene401** [comment]
It worked to downgrade pytorch-geometric to 1.7.2.  Downgrading to 1.6.0 leads to new errors when importing packages :  `ImportError: cannot import name 'container_abcs' from 'torch._six' (/usr/local/lib/python3.7/dist-packages/torch/_six.py)`. for  `from dig.xgraph.dataset import SynGraphDataset`
