### ISSUE TITLE
GCNConv self.weight missing

### ISSUE THREAD

**Issue by spideralessio** [divelab/DIG#57]
in GCNConv, inside the forward function you perform the following operation
`x = torch.matmul(x, self.weight)`

torch geometric has replaced the weight with a linear layer

**Comment by spideralessio** [comment]
you need to replace it with `x = self.lin(x)`

**Comment by Oceanusity** [comment]
Please refer to the issue #54. Due to there are some xgraph methods using the weight in calculation, we won't change the this code now.
