### ISSUE TITLE
Dose bace in the config of xgraph mean MUTAG dataset?

### ISSUE THREAD

**Issue by Zha0nin9-Yu** [divelab/DIG#58]
Hi DIG,
I cannot find the config for dataset MUTAG.
Does bace represent MUTAG?
Thank you,
Zhaoning

**Comment by Oceanusity** [comment]
Bace is another molecule dataset, and it's not MUTAG.

**Comment by Oceanusity** [comment]
We don't provide the config for the MUTAG dataset in the benchmark code. If you are interested in the SubgraphX on the MUTAG, you can refer to the [original code](https://github.com/divelab/DIG/tree/main/dig/xgraph/SubgraphX) for SubgraphX paper. Please keep in mind that the settings in the benchmark and that in the original code are different such as different score functions.
