### ISSUE TITLE
Great toolkit! Is there any schedule to add the OGB datasets to ssl-graph?

### ISSUE THREAD

**Issue by ha-lins** [divelab/DIG#6]
Thanks for this great work! 

I suggest that adding the [OGB dataset](https://github.com/snap-stanford/ogb) to the ssl-graph classification could be more perfect. As far as I know, the OGB benchmark is more challenging and convincing than the TUDataset. Are the developers interested in merging it into DIG? Thanks a lot!

**Comment by ycremar** [comment]
Hi @ha-lins ,

The OGB dataset has not been commonly used in existing SSL studies, but we will definitely consider including the OGB dataset in the near future. In addition, we will include regression tasks for evaluation in the next update.

In the meanwhile, you can manually load datasets from OBG and use them with our library. Our evaluation tools should currently be compatible with any graph classification datasets from OBG.
