### ISSUE TITLE
Reproduction of MD17 results

### ISSUE THREAD

**Issue by Xi-yuanWang** [divelab/DIG#62]
Hi,

I am trying to reproduce energy MAE results of SphereNet on MD17 dataset. I used the `examples/threedgraph/threedgraph.ipynb` in this project but couldn't reproduce. What should be the hyperparameters for results reproduction?

Thanks,
Xiyuan Wang

**Comment by limei0307** [comment]
Hi @Xi-yuanWang,

We focus on force MAE and didn't provide energy MAE on MD17. I re-run our code and provide the trained models and hyperparameters [here](https://github.com/divelab/DIG_storage/tree/main/3dgraph/md17). I will also update the hyperparameters in the example code.

Thanks!

**Comment by Xi-yuanWang** [comment]
Hi @limei0307,
Models work very well. Thanks!
