### ISSUE TITLE
Bug in models GCN

### ISSUE THREAD

**Issue by bene401** [divelab/DIG#65]
Hey there, 

i tried to train the GCN_2l Model and always get this error:

'
/usr/local/lib/python3.7/dist-packages/dig/xgraph/models/models.py in forward(self, x, edge_index, edge_weight)
    323         edge_weight.requires_grad_(True)
    324 
--> 325         x = torch.matmul(x, self.weight)'

AttributeError: 'GCNConv' object has no attribute 'weight'

I can't see were weight is instantiated

**Comment by Oceanusity** [comment]
Please refer to the issue #54 for more details. Install `torch_geometric` with version 1.6.0 can solve this problem.
