### ISSUE TITLE
keys unmatched for SubgraphX.ipynb

### ISSUE THREAD

**Issue by zacharykzhao** [divelab/DIG#66]
when I test the demo for https://github.com/divelab/DIG/blob/dig/examples/xgraph/subgraphx.ipynb, the error rises:

`
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model.load_state_dict(torch.load(ckpt_path)['state_dict'])
  File "module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GCN_2l:
	Missing key(s) in state_dict: "conv1.lin.weight", "convs.0.lin.weight". 
	Unexpected key(s) in state_dict: "conv1.weight", "convs.0.weight". 
`

which corresponds to the last line of [3] in https://github.com/divelab/DIG/blob/dig/examples/xgraph/subgraphx.ipynb.

**Comment by mengliu1998** [comment]
Hi @zacharykzhao,

Thanks for your interest.

It seems that this issue is caused by the PyG version. Could you refer to issue #54? Thanks.

**Comment by zacharykzhao** [comment]
> Hi @zacharykzhao,
> 
> Thanks for your interest.
> 
> It seems that this issue is caused by the PyG version. Could you refer to issue #54? Thanks.

Thanks a lot. I have fixed this problem.
