### ISSUE TITLE
Data inconsistency error.

### ISSUE THREAD

**Issue by zacharykzhao** [divelab/DIG#67]
After downloading the data through:
`
dig.xgraph.dataset.SynGraphDataset('./datasets', 'BA_shapes')
`
When I test PGExplainer, 
`
splitted_dataset.slices['mask'] = splitted_dataset.slices['train_mask']
`

the error occurs:

`
splitted_dataset.slices['mask'] = splitted_dataset.slices['train_mask']
TypeError: 'NoneType' object is not subscriptable
`

May I have any suggestions? THX

**Comment by Oceanusity** [comment]
Hello, thank you for your issue. Would you mind sharing the specific error information including the trackback and corresponding codes?

**Comment by zacharykzhao** [comment]
> 

Thank you very much. I have fixed by your previous reply.

**Comment by Never-yu** [comment]
@zacharykzhao  Hi, I also encountered this problem. Could you please tell me how to solve this problem? Thank you very much.

**Comment by cxw-droid** [comment]
Same issue. 

>    splitted_dataset.slices['mask'] = splitted_dataset.slices['train_mask']
TypeError: 'NoneType' object is not subscriptable

The code is `examples/xgraph/pgexplainer.ipynb`. I am using torch-geometric 2.1.0. Could any one please take a look? Thanks

**Comment by zacharykzhao** [comment]
> @zacharykzhao Hi, I also encountered this problem. Could you please tell me how to solve this problem? Thank you very much.

@Never-yu I remember this API implements the data split operation. The error should be caused by data structure mismatching. As I used my own dataset, I just replace the API and implement my own datasplit function.
