### ISSUE TITLE
Bug at forward-Method of pgexplainer

### ISSUE THREAD

**Issue by bene401** [divelab/DIG#68]
Hello, 

when I try to run the code of the Example-Notebook for a graph-classification problem I get this error: 

`---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-107-d54bfebc885b> in <module>()
     22   # Speichern der Werte in XCollector
     23   with torch.no_grad():
---> 24       walks, masks, related_preds = explainer(x, edge_index, top_k=top_k)
     25       masks = [mask.detach() for mask in masks]
     26 

1 frames
/usr/local/lib/python3.7/dist-packages/dig/xgraph/method/pgexplainer.py in forward(self, x, edge_index, **kwargs)
    757         pred_mask = [edge_mask]
    758         related_preds = [{
--> 759             'masked': masked_pred,
    760             'maskout': maskout_pred,
    761             'origin': probs[label],

UnboundLocalError: local variable 'masked_pred' referenced before assignment`

When looking at the source code it seems, that masked_pred is only for node classification defined. 
Thanks for help

**Comment by Oceanusity** [comment]
Thank you for your issue.
I have fixed this bug in the repo, and it will be updated in the next version package.
Welcome to post an issue if you have further problems.

**Comment by bene401** [comment]
thanks for the fast answer
