### ISSUE TITLE
Evaluation of SubgraphX vs rest

### ISSUE THREAD

**Issue by mbajaj01** [divelab/DIG#7]
Is there a reason some of the methods are evaluated for fidelity by zeroing out the node features, and for subgraphX it seems that the fidelity is being reported as the output of the subgraph itself which is not consistent with the definition of fidelity. Could you please elaborate more on this? Also zeroing out the features should change the data distribution itself as the model might not have seen nodes with 0 features before, so why use zeroing out?

**Comment by divelab** [comment]
Thanks for your questions. 

First, for all methods, the zeroing out is applied. For our method, we set the features of the nodes in our subgraphs as 0. For other methods, such as GNNExplainer, we zeroing out the nodes connected with important edges. Details can be found in our paper Appendix A.3.  For the code part, we also realized the issue yesterday.  We checked our code and found we merged the wrong version of different files. Then there are some inconsistencies among different function names. We will fix it soon! Sorry for any confusion and inconvenience. 

Second, zeroing out the features means the unimportant nodes have all zeros features. By zeroing out a node, this node is available for passing information from neighbors to neighbors. However, this node's features will not contribute to their neighbor's features.  Intuitively, this is what we need to study the impact of different structures. Again, we wish to mention that there is no standard way to mask out graph data. Considering the trade-off between structural change and feature change, we believe zeroing out is a proper choice.
