### ISSUE TITLE
Version of package

### ISSUE THREAD

**Issue by lx19930** [divelab/DIG#74]
Hi,
I am trying to install and test this package, but it seems that the newest pyg wouldn't work. May I ask what version of the following packages did you use when creating DIG?
pytorch and torch-scatter, torch-sparse, torch-geometric, torch-cluster, torch-spline-conv
Thank you so much

**Comment by mengliu1998** [comment]
Hi @lx19930,

Thank you for your interest.

As shown in our [installation instruction](https://github.com/divelab/DIG#install-from-pip), we should install PyTorch >= 1.6.0 and PyG between 1.6.0 and 1.7.2. For other dependencies of PyG, such as torch-scatter and torch-sparse, you can follow the instruction of PyG to install the corresponding versions. For example, if you plan to install PyG 1.6.1, you can follow [this](https://pytorch-geometric.readthedocs.io/en/1.6.1/notes/installation.html) to install PyG, along with torch-scatter, torch-sparse, torch-cluster and torch-spline-conv. 

Please let me know if you have any further questions.

**Comment by lx19930** [comment]
Dear Meng,
Thank you for your quick response. I have some trouble installing the
latest version of torch-scatter and torch-sparse with pytorch=1.6.0. The
error is not there when installing with torch=1.10.0 so my guess is the
newest version of these two packages does not play well with torch 1.6.0.
The website you mentioned provides an instruction suggesting
pip install torch-scatter==latest+${CUDA} -f
https://pytorch-geometric.com/whl/torch-${TORCH}.html
which doesn't work in my environment.
Is it possible that you can show me which version of torch-scatter and
torch-sparse are you using?
Thank you so much
Xing

**Comment by lx19930** [comment]
I just installed your package with the following commands:

conda create -n python=3.7 pip
pip install torch==1.6.0 torchvision==0.7.0
pip install torch-scatter==2.0.5 -f
https://pytorch-geometric.com/whl/torch-1.6.0+cu102.html
pip install torch-sparse==0.6.8 -f
https://pytorch-geometric.com/whl/torch-1.6.0+cu102.html
pip install torch-geometric==1.6.0
pip install tensorboard
pip install torch-cluster==1.5.9 -f
https://pytorch-geometric.com/whl/torch-1.6.0+cu102.html
pip install dive-into-graphs

in case anyone else needs to know.

**Comment by mengliu1998** [comment]
Hi @lx19930,

I am using the specific environment with pytorch=1.6.0, torch-geometric(PyG)=1.7.0, torch-cluster=1.5.9, torch-scatter=2.0.6, torch-sparse=0.6.9, and torch-spline-conv=1.2.1.

Again, it would be better to install the corresponding dependency versions for PyG. You can find all the wheels [here](https://pytorch-geometric.com/whl/).
