### ISSUE TITLE
Is DIG model agnostic?

### ISSUE THREAD

**Issue by golubovic** [divelab/DIG#76]
Hi,

Is DIG Model agnostic? I would appreciate it if you can point me towards a guide/examples which show how can we use DIG explainability with existing GNN models developed in PyG, DGL or any other library. 

Essentially the question is can DIG be used as an 'explainability wrapper' around existing graph models (which aren't developed using DIG library)?

Happy new year!

Thanks,
Mladen

**Comment by Oceanusity** [comment]
Hello Mladen,

Thank you for your issue and it's a good question. 

For the model-agnostic part, it depends on the methods. For example, the SubgraphX is a model-agnostic method while the gnnlrp isn't.

For the wrapper part, the methods that aren't model-agnostic can't be apply on the existing PyG or DGL models. But we provide model implementation to use these methods.
https://github.com/divelab/DIG/blob/bcc2d349962b6a504521959957625dd9198dad88/benchmarks/xgraph/gnnNets.py#L16
https://github.com/divelab/DIG/blob/bcc2d349962b6a504521959957625dd9198dad88/dig/xgraph/models/models.py#L51

For the model-agnostic method, SubgraphX can be directly used if you provide an input parser in the forward funciton to allow flexible input format. Please refer to issue #75.
https://github.com/divelab/DIG/blob/bcc2d349962b6a504521959957625dd9198dad88/dig/xgraph/models/models.py#L26

**Comment by golubovic** [comment]
Thank you for the quick response
