### ISSUE TITLE
QM9 and SphereNet example error

### ISSUE THREAD

**Issue by yuanqidu** [divelab/DIG#77]
Great work!

When I copied the code from the README file and run it with the QM9 dataset provided by DIG, it showed me the following error when I attempt to create a SphereNet model.

Traceback (most recent call last):
  File "main_qm9.py", line 19, in <module>
    model = SphereNet(energy_and_force=False, cutoff=5.0, num_layers=4,
  File "/opt/conda/lib/python3.8/site-packages/dig/threedgraph/method/spherenet/spherenet.py", line 265, in __init__
    self.emb = emb(num_spherical, num_radial, self.cutoff, envelope_exponent)
  File "/opt/conda/lib/python3.8/site-packages/dig/threedgraph/method/spherenet/spherenet.py", line 23, in __init__
    self.dist_emb = dist_emb(num_radial, cutoff, envelope_exponent)
  File "/opt/conda/lib/python3.8/site-packages/dig/threedgraph/method/spherenet/features.py", line 178, in __init__
    self.reset_parameters()
  File "/opt/conda/lib/python3.8/site-packages/dig/threedgraph/method/spherenet/features.py", line 181, in reset_parameters
    torch.arange(1, self.freq.numel() + 1, out=self.freq).mul_(PI)
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

**Comment by limei0307** [comment]
Hi @yuanqidu,

Thanks for your interest in our work.

I didn't have this issue. Could you try to replace [line 176 to 181](https://github.com/divelab/DIG/blob/dig/dig/threedgraph/method/spherenet/features.py#L176)
```
        self.freq = torch.nn.Parameter(torch.Tensor(num_radial))

        self.reset_parameters()

    def reset_parameters(self):
        torch.arange(1, self.freq.numel() + 1, out=self.freq).mul_(PI)
```
with
```
self.freq = torch.nn.Parameter(
            data=torch.tensor(
                np.pi * np.arange(1, num_radial + 1, dtype=np.float32)
            ),
            requires_grad=True,
        )
```
Does it solve your problem?

Thanks

**Comment by zoexu119** [comment]
Hi @yuanqidu,

I also met this issue and believe it's due to the PyTorch version. You can also try to replace line 181 to be

```
self.freq.data = torch.arange(1, self.freq.numel() + 1).float().mul_(PI)
```

**Comment by vinayak2019** [comment]
> Hi @yuanqidu,
> 
> I also met this issue and believe it's due to the PyTorch version. You can also try to replace line 181 to be
> 
> ```
> self.freq.data = torch.arange(1, self.freq.numel() + 1).float().mul_(PI)
> ```

This did not work for me. Neither did the first solution. There is a dependency in [spherenet.py](https://github.com/divelab/DIG/blob/dig/dig/threedgraph/method/spherenet/spherenet.py) line 29 which still causes an error
```
class emb(torch.nn.Module):
    def __init__(self, num_spherical, num_radial, cutoff, envelope_exponent):
        super(emb, self).__init__()
        self.dist_emb = dist_emb(num_radial, cutoff, envelope_exponent)
        self.angle_emb = angle_emb(num_spherical, num_radial, cutoff, envelope_exponent)
        self.torsion_emb = torsion_emb(num_spherical, num_radial, cutoff, envelope_exponent)
        self.reset_parameters()

    def reset_parameters(self):
        self.dist_emb.reset_parameters()
```

**Comment by limei0307** [comment]
Hi @vinayak2019, 

Could you please provide more detail about the error? Thanks.
Besides, please install 'sympy' via 'pip install sympy'.

Thanks.

**Comment by vinayak2019** [comment]
When I replace [line 176 to 181](https://github.com/divelab/DIG/blob/dig/dig/threedgraph/method/spherenet/features.py#L176) with the suggestion above I get the following error.  

```Traceback (most recent call last):
  File "sphere.py", line 20, in <module>
    model = SphereNet(energy_and_force=False, cutoff=5.0, num_layers=4,
  File "/home/vbh226/.local/lib/python3.8/site-packages/dig/threedgraph/method/spherenet/spherenet.py", line 266, in __init__
    self.emb = emb(num_spherical, num_radial, self.cutoff, envelope_exponent)
  File "/home/vbh226/.local/lib/python3.8/site-packages/dig/threedgraph/method/spherenet/spherenet.py", line 26, in __init__
    self.reset_parameters()
  File "/home/vbh226/.local/lib/python3.8/site-packages/dig/threedgraph/method/spherenet/spherenet.py", line 29, in reset_parameters
    self.dist_emb.reset_parameters()
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'dist_emb' object has no attribute 'reset_parameters'
```
In this case I delete the following lines in [features.py](https://github.com/divelab/DIG/blob/dig/dig/threedgraph/method/spherenet/features.py)
```
        self.reset_parameters()

    def reset_parameters(self):
        torch.arange(1, self.freq.numel() + 1, out=self.freq).mul_(PI)
```
The error is expected as `reset_parameters` is no longer defined.

When I add lines backs to the file, while still modifying the `self.freq` I get the following error.

```
Traceback (most recent call last):
  File "sphere.py", line 20, in <module>
    model = SphereNet(energy_and_force=False, cutoff=5.0, num_layers=4,
  File "/home/vbh226/.local/lib/python3.8/site-packages/dig/threedgraph/method/spherenet/spherenet.py", line 266, in __init__
    self.emb = emb(num_spherical, num_radial, self.cutoff, envelope_exponent)
  File "/home/vbh226/.local/lib/python3.8/site-packages/dig/threedgraph/method/spherenet/spherenet.py", line 23, in __init__
    self.dist_emb = dist_emb(num_radial, cutoff, envelope_exponent)
  File "/home/vbh226/.local/lib/python3.8/site-packages/dig/threedgraph/method/spherenet/features.py", line 181, in __init__
    self.reset_parameters()
  File "/home/vbh226/.local/lib/python3.8/site-packages/dig/threedgraph/method/spherenet/features.py", line 184, in reset_parameters
    torch.arange(1, self.freq.numel() + 1, out=self.freq).mul_(PI)
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
```

If I now set `self.freq.data = torch.arange(1, self.freq.numel() + 1).float().mul_(PI)`. I still get the leaf Variable error. 
The only way I could get it working is by doing this
```
class dist_emb(torch.nn.Module):
    def __init__(self, num_radial, cutoff=5.0, envelope_exponent=5):
        super(dist_emb, self).__init__()
        self.cutoff = cutoff
        self.envelope = Envelope(envelope_exponent)
        self.freq = torch.nn.Parameter(
            data=torch.tensor(
                np.pi * np.arange(1, num_radial + 1, dtype=np.float32)
            ),
            requires_grad=True,
        )
        self.reset_parameters()

    def reset_parameters(self):
       # self.freq.data = torch.arange(1, self.freq.numel() + 1, out=self.freq).mul_(PI)
       pass

```
I don't know how correct that is.

I am using 
torch==1.11.0
dive-into-graphs (cloned from GitHub. The pip install has a bug [line 53](https://github.com/divelab/DIG/blob/dig/dig/threedgraph/utils/geometric_computing.py#L53) mask is missing)

**Comment by limei0307** [comment]
Hi @vinayak2019,

I think for the first solution, you can just remove the "self.dist_emb.reset_parameters()" in spherenet.py [line 21 to 24](https://github.com/divelab/DIG/blob/dig/dig/threedgraph/method/spherenet/spherenet.py#L21) since the function doesn't need to reset_parameter.

For the second solution, could you provide the detailed error output?

Yes, you can just clone the code from GitHub since we update the code after the latest pip install version (0.1.2). But it seems that you are using the package via 'pip install', not the code cloned from Github since your path is ```lib/python3.8/site-packages/dig```.

Thanks.

**Comment by limei0307** [comment]
Hi @vinayak2019,
Ok. I will close this issue.
