### ISSUE TITLE
XGNN code is giving lower accuracy than reported in the paper

### ISSUE THREAD

**Issue by hammad26** [divelab/DIG#78]
Hi
Hope that you will be fine. In the paper of XGNN, reported accuracy on MUTAG dataset is 0.963 whereas when I used the given code of XGNN I am getting 0.936. So, roughly given code is 2.7% lower in accuracy. Can you guide why this is happening and how can I achieve the accuracy which is reported in the XGNN paper? Thanks
![image](https://user-images.githubusercontent.com/12643784/148766547-4d2d3119-4970-4119-ada8-47df814d8958.png)
![image](https://user-images.githubusercontent.com/12643784/148766672-d5d98e77-354f-48c2-a877-829bbc764e51.png)

**Comment by Nate1874** [comment]
Thanks for the question. 
I do not have the GNN model and only kept the original dataset since our goal is to explain any reasonable model. 
I believe explaining any GNN model with good performance is reasonable so you can just use the one with 0.936 performance as the target.
