### ISSUE TITLE
SubgraphX is taking too long to run

### ISSUE THREAD

**Issue by Mandeep-Rathee** [divelab/DIG#79]
hello dear,

thank you so much for the wonderful library. 

I am having a run time problem while executing SubgraphX. For explaining a single node my code is taking a few hours.  I am using a GCN model to train the synthetic dataset; This is how my model looks like:

**GCN
  (conv1): GCNConv(10, 20)
  (conv2): GCNConv(20, 20)
  (lin_pred): Linear(in_features=40, out_features=8, bias=True)
)**

I am using the synthetic dataset where features are from a normal distribution:
     **Dataset(num_node_features=10, num_classes=8)
     Data(edge_index=[2, 8920], test_mask=[1400], train_mask=[1400], x=[1400, 10], y=[1400])**

I am using the following dependencies:

**Cuda=10.2
dive-into-graphs          0.1.2                 
torch                          1.10.1                   
torch-geometric        1.7.2                  
torch-scatter             2.0.9                   
torch-sparse             0.6.12                   
torchaudio                0.10.1                  
torchvision                0.11.2** 
         
Is this time taken by SubgraphX is normal or I am doing some mistake? Can you please help me with this? 

thanks in advance!!

**Comment by Oceanusity** [comment]
Thank you for your issue.

SubgraphX will cost a lot of time to explore the subgraphs especially when the subgraphs contain a lot of nodes and edges. You can find the time consumption through the [paper](https://arxiv.org/pdf/2102.05152.pdf). When the subgraph is about 25 nodes, it will cost about 1.5 minute to explore the state.

If the subgraph contains more than 100 nodes, it's possible to take one hour or more to get the final results.
