### ISSUE TITLE
Running SubgraphX on arbitrary datasets

### ISSUE THREAD

**Issue by nprasadmm** [divelab/DIG#80]
I am confused as to how I would run SubgraphX on my GCN model with my own created datasets. My datasets are collections of `torch_geometric.data.Data` objects with the expected attributes. However `PlotUtils` seems to require me to choose from a set of dataset names, which are not relevant to my dataset. How do I produce the visualization after executing the code below? The API does not seem to allow me to specify the node labels.

         explainer = SubgraphX(model, num_classes=2,  device=torch.device('cuda:0'))
        _, explanation_results, related_preds = explainer(data.x.cuda(), data.edge_index.cuda(), max_nodes=10)

**Comment by Oceanusity** [comment]
Hello, the visualization code is highly related to the dataset.  For example, molecule datasets use different colors for atoms while synthethic datasets use different colors for nodes with different labels. In this case, I recommend you to refer to the implementation of the visualization function and modifies it to fit your own dataset.
