### ISSUE TITLE
Link Prediction

### ISSUE THREAD

**Issue by apratim-mishra** [divelab/DIG#82]
Can someone give me a basic overview of how to proceed for explanation on a link prediction task.
I built the node embeddings and the link prediction class in Pytorch geometric. 
can I use DIG with PYG models for link prediction

**Comment by Oceanusity** [comment]
Thank you for your issue.

For the link prediction task, I think you can take it as node classification task, and change the node class prediction into link prediction. In this way, you can use the explanation methods applied on the node classification task.
