### ISSUE TITLE
Self-Supervised GNNs

### ISSUE THREAD

**Issue by abrahami** [divelab/DIG#83]
hi!
I am trying to use the implementation of the self-supervised GNNs (e.g., InfoGraph). However, the [example provided](https://github.com/divelab/DIG/blob/dig/examples/sslgraph/example_infograph.ipynb) is using a graph dataset that is labeled and actually evaluate the model by using sklearn supervised evaluation process.
I am looking for an end-to-end example of applying the algorithm in an unsupervised way and get an embeddings representation per graph.

thanks a lot!

**Comment by ycremar** [comment]
Hi @abrahami ,

Thank you for your question. Following the example, once the model is trained, you can obtain the embedding of any graph `data` by `embed = encoder(data)`.

For more flexibility, you can manually train the model without downstream evaluation by

`infograph.train(encoder, pretrain_dataloader, optimizer, num_epoches)`

and then `embed = encoder(data)`.

Please let us know if you have any further questions!
