### ISSUE TITLE
train_gnns.sh not working

### ISSUE THREAD

**Issue by cxw-droid** [divelab/DIG#84]
Hi, I want to train on some new dataset and I tried to run train_gnns.sh to see if the original code works and then I can modify it as needed. It output errors:
```
train_gnns.py", line 90, in train_GC
    dataset = get_dataset(data_args)
TypeError: get_dataset() missing 1 required positional argument: 'dataset_name'
```
It seems the original code is no long working. Can you please take a look at this? Thanks.

**Comment by mengliu1998** [comment]
Hi @cxw-droid,

Thank you for your interest. It seems that there is no given data_args. Could you provide more details about the issue, such as the link for the corresponding code file and your used command? Thank you.

**Comment by cxw-droid** [comment]
When I ran [train_gnns.sh](https://github.com/divelab/DIG/blob/main/dig/xgraph/SubgraphX/models/train_gnns.sh) using command `source train_gnns.sh` or`sh trains_gnn.sh`., an error was thrown at line 90 of file [train_gnns.py](https://github.com/divelab/DIG/blob/main/dig/xgraph/SubgraphX/models/train_gnns.py). It seems the interface of `get_dataset` was already changed. 

Also last week I tried to run the second command (i.e. using mutag dataset) of  [train_gnns.sh](https://github.com/divelab/DIG/blob/main/dig/xgraph/SubgraphX/models/train_gnns.sh) after commenting out the first command and uncommenting the second command, it output error too. You can try to run [train_gnns.sh](https://github.com/divelab/DIG/blob/main/dig/xgraph/SubgraphX/models/train_gnns.sh) using mutag dataset and see the error message.

**Comment by Oceanusity** [comment]
Hello, I have updated the train_gnns.py and used the new API. Thank you for your issue.
