### ISSUE TITLE
Issue on running example gradcam.ipynb

### ISSUE THREAD

**Issue by Kemp11** [divelab/DIG#87]
When I run the codes in the "Display example output": out = model(data.x, data.edge_index)
I got the error message:

[AttributeError: 'GINConv' object has no attribute '__explain__']()

Could someone give me a hint on how to solve this issue?

**Comment by AntonioLonga** [comment]
Hello to all, 

thanks a lot for the library.

I have the same issue.
Does someone have any idea?

Thanks a lot in advance

**Comment by CM-BF** [comment]
Sorry for the late reply. Can you provide your environment and the log?

**Comment by CM-BF** [comment]
And we are actively updating the DIG version to support the latest PyG and PyTorch. We make sure that this will be solved soon.

**Comment by CM-BF** [comment]
Solved on [dig-stable branch](https://github.com/divelab/DIG/tree/dig-stable).
