### ISSUE TITLE
Environment issue about PGExplainer

### ISSUE THREAD

**Issue by crop-leaderboard** [divelab/DIG#88]
What is the version of torch-geometric are you using? It seems that there is an error message **AttributeError: module 'torch.nn.parameter' has no attribute 'UninitializedParameter'** when I use version 2.0.3 and an error message **KeyError: 'model.gnn_layers.0.lin.weight'** when I use version 2.0.4.

**Comment by Liyiqiao** [comment]
I have met the same problem before. But when I installed install pytorch 1.11.0, torch-scatter 2.0.9, torch-sparse 0.6.13, and torch-geometric 1.7.0. I can run the gnnexplainer.ipynb now.
