### ISSUE TITLE
Problem with subgraphx gnns calling find closest node result

### ISSUE THREAD

**Issue by Hannnne** [divelab/DIG#95]
Hi,

When calling closest node result for metric score as suggest in example examples/xgraph/subgraphx.ipynb.

like this:
```
_, explanation_results, related_preds = \
        explainer(data.x, data.edge_index, node_idx=node_idx, max_nodes=max_nodes)

    explanation_results = explanation_results[prediction]
    explanation_results = explainer.read_from_MCTSInfo_list(explanation_results)
    result = find_closest_node_result(explanation_results, max_nodes=max_nodes)
```
I am getting following error
```
 results = sorted(results, key=lambda x: len(x.coalition))
AttributeError: 'dict' object has no attribute 'coalition'
```
I fixed it by offering an option for dictionaries, but I am still wondering why it happens.
Can someone give me a hint, why that is happening?

Thank you
Hanne

**Comment by Oceanusity** [comment]
Sorry for the late reply, and this problem surprises me too. From the code, the `explanation_results` save a list of dictionaries, and [read_from_MCTSInfo_list](https://github.com/divelab/DIG/blob/aaf7f5f09a03b0067d995c70f0c599f6f2eed5f7/dig/xgraph/method/subgraphx.py#L733) loads the list of dictionaries to a list of `MCTSNode`.  Therefore, the `explanation_results` passed to `find_closest_node_result`  should be a list of `MCTSNode`. However, this error shows that this variable is a list of dictionaries, which is not expected.

**Comment by Oceanusity** [comment]
Welcome to reopen this issue if you still have this problem.
