### ISSUE TITLE
QM9 and SphereNet example error

### ISSUE THREAD

**Issue by vinayak2019** [divelab/DIG#96]
> Hi @yuanqidu,
> 
> I also met this issue and believe it's due to the PyTorch version. You can also try to replace line 181 to be
> 
> ```
> self.freq.data = torch.arange(1, self.freq.numel() + 1).float().mul_(PI)
> ```

This did not work for me. Neither did the first solution. There is a dependency in [spherenet.py](https://github.com/divelab/DIG/blob/dig/dig/threedgraph/method/spherenet/spherenet.py) line 29 which still causes an error
```
class emb(torch.nn.Module):
    def __init__(self, num_spherical, num_radial, cutoff, envelope_exponent):
        super(emb, self).__init__()
        self.dist_emb = dist_emb(num_radial, cutoff, envelope_exponent)
        self.angle_emb = angle_emb(num_spherical, num_radial, cutoff, envelope_exponent)
        self.torsion_emb = torsion_emb(num_spherical, num_radial, cutoff, envelope_exponent)
        self.reset_parameters()

    def reset_parameters(self):
        self.dist_emb.reset_parameters()
```

**Comment by limei0307** [comment]
Please see [issue #77](https://github.com/divelab/DIG/issues/77).
